### ISSUE TITLE
@utbot.triggersRecursion tag is missing

### ISSUE THREAD

**Issue by alisevych** [UnitTestBot/UTBotJava#1014]
**Description**

@utbot.triggersRecursion tag is missing for Recursion.fib(int n) tests

**To Reproduce**

1. Run the UTBot project in IntelliJ Idea 2022.1.4
2. Install [plugin ](https://github.com/UnitTestBot/UTBotJava/actions/runs/3127050936)
3. Check: File -> Settings -> Tools -> UnitTestBot -> Javadoc comment style is "Structured via custom Javadoc tags"
4. Open the utbot-sample/src/main/java/org/utbot/examples/recursion/Recursion.java file
5. Generate tests for the methods
6. Open the generated test

**Expected behavior**

Tests with input n >= 1 are supposed to have @utbot.triggersRecursion tag in Java doc.

**Actual behavior**

Tests with input (n = 1), (n = 2) do not have @utbot.triggersRecursion tag in Java doc.

**Visual proofs (screenshots, logs, images)**

~~~java
    /**
     * @utbot.classUnderTest {@link Recursion}
     * @utbot.methodUnderTest {@link Recursion#fib(int)}
     * @utbot.executesCondition {@code (n == 1): False}
     * @utbot.returnsFrom {@code return fib(n - 1) + fib(n - 2);}
     */
    @Test
    @DisplayName("fib: return 1 -> return 0")
    public void testFib_NNotEquals1() {
        Recursion recursion = new Recursion();

        int actual = recursion.fib(2);

        assertEquals(1, actual);
    }
~~~

**Environment**

Windows 10 Pro
Gradle project
JDK 11

**Comment by amandelpie** [comment]
Thanks @alisevych , probably it will be fixed in the next release looks like missed and unsupported functionlity

**Comment by amandelpie** [comment]
With Symbolic Execution = 95% I've obtained 

```
    /**
     * @utbot.classUnderTest {@link Recursion}
     * @utbot.methodUnderTest {@link Recursion#fib(int)}
     * @utbot.executesCondition {@code (n < 0): False}
     * @utbot.executesCondition {@code (n == 0): False}
     * @utbot.executesCondition {@code (n == 1): False}
     * @utbot.triggersRecursion fib, where the test execute conditions:
     * {@code (n == 1): True}
     * return from: {@code return 1;}
     * @utbot.returnsFrom {@code return fib(n - 1) + fib(n - 2);}
     */
    @Test
    @DisplayName("fib: n == 1 : True -> return 0")
    public void testFib_NEquals1() {
        Recursion recursion = new Recursion();

        int actual = recursion.fib(2);

        assertEquals(1, actual);
    }
```

Looks like we have the same test but with different metadata

**Comment by alisevych** [comment]
@amandelpie Not reproducing for me either - on the latest main. Verified on IDEA 2022.1.4 and 2022.2.3
