### ISSUE TITLE
NullPointerException: null when invoking CollectionWrappersKt.constructKeysAndValues

### ISSUE THREAD

**Issue by alexeyfridman** [UnitTestBot/UTBotJava#107]
**Description**

NullPointerException when invoking CollectionWrappersKt.constructKeysAndValues

**To Reproduce**

1. Run the `UTBotTest` project in IntelliJ Idea
2. Use plugin to generate tests for `MapOperate` method
3. Open the generated test

**Expected behavior**

Tests are supposed to be generated.

**Actual behavior**

NullPointerException 

**Visual proofs (screenshots, logs, images)**

Method under test:
```kotlin
public List<String> mapOperator(Map<String, String> map) {
    List<String> result = new ArrayList<>();
    for (Map.Entry<String, String> entry : map.entrySet()) {
        if (entry.getKey().equals("key")) {
            result.add(entry.getValue());
        }
    }
    if (result.size() > 3) {
        return result;
    } else {
        return new ArrayList<>(map.values());
    }
}
```

**Environment**

The default one.

**Additional context**

There is no additional context.

**Comment by CaelmBleidd** [comment]
Checked. There is no NPE anymore, but there is a problem with failed tests inside `org.utbot.engine.pc.UnsatQuery#with`. Because of some reason now `org.utbot.engine.Traverser#initStringLiteral` changes a state status into `UNSAT` and we get an error there.
