### ISSUE TITLE
Java docs with plain text are rendered incorrectly

### ISSUE THREAD

**Issue by alisevych** [UnitTestBot/UTBotJava#1078]
**Description**

Java docs with plain text are rendered incorrectly.

**To Reproduce**

1. Run UTBotJava project in IntelliJ Idea 2022.1.4
2. Set Java doc style to "Plain text"
3. Open utbot-sample/src/main/java/org/utbot/examples/algorithms/ArraysQuickSort.java
4. Use plugin to generate tests - [one of the latest builds from main](https://github.com/UnitTestBot/UTBotJava/actions/runs/3180887399)
5. Open the generated test

**Expected behavior**

Information in Java docs is supposed to be correctly displayed in rendered mode.

**Actual behavior**

Java docs are displayed as one blank string in rendered mode.

**Visual proofs (screenshots, logs, images)**

![image](https://user-images.githubusercontent.com/37301492/193799295-53ba6f27-8bcd-42de-9700-85ea5974f61e.png)

![image](https://user-images.githubusercontent.com/37301492/193799306-31d701e2-3e95-45d7-84b6-fe86e9c91310.png)

**Environment**

WIndows 10 Pro
IntelliJ IDEA 2022.1.4

**Additional context**

Also reproducing in IDEA 2022.2.2 - with plugin from #1067 

Also applicable for UtUtils class methods Java docs:

![image](https://user-images.githubusercontent.com/37301492/193833534-cb55093b-0f57-4f22-b0ac-a2789882138c.png)

![image](https://user-images.githubusercontent.com/37301492/193833594-5e06ea9d-d44d-408e-93fb-3c5283c96afa.png)

_Originally posted by @alisevych in https://github.com/UnitTestBot/UTBotJava/issues/1068#issuecomment-1266751577_

**Comment by alisevych** [comment]
@amandelpie FYI

**Comment by amandelpie** [comment]
Yes, I discover the same thing today

**Comment by amandelpie** [comment]
@alisevych should we include this into release?
