### ISSUE TITLE
Remove redundant `.` in published artifacts

### ISSUE THREAD

**Issue by victoriafomina** [UnitTestBot/UTBotJava#1158]
**Description**

Redundant `.` symbol is added when plugin and CLI are published on `push`.

**To Reproduce**

1. Open **Actions** section
2. Choose `Plugin and CLI: publish as archives` workflow
3. Click on workflow run
4. See what's described in _Description_ section

**Expected behavior**

_Example:_ Tests are supposed to be generated.

**Actual behavior**

_Example:_ An error test is generated with information about errors in the concrete executor.

**Visual proofs (screenshots, logs, images)**

![image](https://user-images.githubusercontent.com/32179813/195824905-435f388d-c027-45e5-8791-ba1e9d459834.png)

**Environment**

GitHub Actions

**Additional context**

No context.

**Comment by alisevych** [comment]
The `.` is still present in artefacts' names - generated automatically from main branch.

Also there is not postfix for manually generated ones - from a branch. Because 'no-postfix-prod' is chosen by default.
