### ISSUE TITLE
Java docs with tags. Link to UnsafeWithField.setField is not resolved

### ISSUE THREAD

**Issue by alisevych** [UnitTestBot/UTBotJava#1172]
**Description**

Java docs with custom tags. Link to UnsafeWithField.setField method is red as it is not not resolved.

**To Reproduce**

1. Run the 'UTBotJava' project in IntelliJ Idea
2. Symbolic analysis is enabled (File -> Settings -> Tools -> UnitTestBot)
3. UnitTestBot plugin is installed from main (checked with two today's versions: https://github.com/UnitTestBot/UTBotJava/actions/runs/3265745363
https://github.com/UnitTestBot/UTBotJava/actions/runs/3259341553
4. In Project view find utbot-sample/src/main/java/org/utbot/examples/unsafe/UnsafeWithField.java
5. Generate tests with UnitTestBot... for it
6. Wait tests are generated

**Expected behavior**

Links to code from Java docs are supposed to be resolved.

**Actual behavior**

Link to UnsafeWithField.setField method is red as it is not not resolved.

**Visual proofs (screenshots, logs, images)**

![image](https://user-images.githubusercontent.com/37301492/196209986-e0700f5e-8df1-48e0-999f-89bfb4b1b16a.png)

![image](https://user-images.githubusercontent.com/37301492/196209837-f022141c-4410-4614-bf25-fb3c620692bf.png)

**Environment**

Windows 10 Pro
IntelliJ IDEA 2022.1.4 (JBR 11)

**Comment by amandelpie** [comment]
The problem is related to incorrect full class name with the $ for the static inner class representation
