### ISSUE TITLE
Check plugin compatibility with IntelliJ IDEA versions

### ISSUE THREAD

**Issue by victoriafomina** [UnitTestBot/UTBotJava#1181]
**Description**

In `build.gradle.kts` for plugin there are specified IntelliJ IDEA versions we suppose the plugin is compatible with.

```gradle
patchPluginXml {
        sinceBuild.set("212")
        untilBuild.set("222.*")
        version.set(semVer)
    }
```

Unfortunately, testers cannot test the plugin on all of the latest versions. So it's possible someone uses the feature making the plugin incompatible with one of the specified versions. And we will know about it only after publication on JetBrains Marketplace.

**Expected behavior**

Workflow checking plugin's binary compatibility with the specified in `build.gradle.kts` IntelliJ IDEA versions.

**Environment**

GitHub Actions

**Context**

No context.

**Comment by alisevych** [comment]
@victoriafomina 
It seems that this task is not important for now.
IDE API changes from version to version, our latest UnitTestBot plugins are compatible with 1-2 IDE versions only.
