### ISSUE TITLE
Server.EngineProcessModel.generateTestReport is not bound to a protocol

### ISSUE THREAD

**Issue by mmvpm** [UnitTestBot/UTBotJava#1183]
**Description**

An error `Cannot save tests generation report: error occurred 'Server.EngineProcessModel.generateTestReport::> is not bound to a protocol’` has occurred after successful test generation.

**To Reproduce**

*Second scenario*

1. Start test generation
2. Open some dialog blocking actions in IDEA
- Git -> Revert
or
- File -> Settings
3. Keep it opened till generation is ended.
4. Close dialog

*First scenario*

1. Create a new project / or open existing
5. Initialize a git repository
6. Select the project directory
7. Use plugin to generate tests
8. Minimize the IDEA window, i.e. switch to any another window
9. Just wait 2-3 minutes
10. Click on the "Cancel" button
 
**Expected behavior**

No errors

**Actual behavior**

![image](https://user-images.githubusercontent.com/54814796/196645976-b7e55990-64d2-419f-a362-267b027c65e9.png)

**Comment by alisevych** [comment]
Reproducing together with the bug:
- #1794

**Comment by alisevych** [comment]
Reproducing with default generation settings on `org.utbot.examples.mock.aliasing.AliasingInParamsExample.example`

![image](https://user-images.githubusercontent.com/37301492/221541691-a23c5ef6-6821-48f1-b1c6-bb545707ebd1.png)

**Comment by alisevych** [comment]
Reproducing again on main on generating tests for `utbot-sample/src/main/java/org/utbot/examples/algorithms/Sort.java`
with Symbolic-100% mode and `Do not mock` selected.
