### ISSUE TITLE
Empty region names and missing javadoc for `Sort.arrayCopy`

### ISSUE THREAD

**Issue by tyuldashev** [UnitTestBot/UTBotJava#1204]
**Description**

**To Reproduce**

```java
    public int[] arrayCopy() {
        int[] fst = {1, 2, 3};
        int[] snd = {4, 5, 6};

        System.arraycopy(fst, 0, snd, 0, 3);
        return snd;
    }
```

1. Open [`algorithms/Sort.java`](https://github.com/UnitTestBot/UTBotJava/blob/main/utbot-sample/src/main/java/org/utbot/examples/algorithms/Sort.java) sample from UTBot project 
2. Or use code sample from above.
3. In plugin settings set generation method to 95% Symbolic
4. Use plugin to generate tests
5. Open the generated test

**Expected behavior**

Every test is placed in region with name and has proper java doc description

**Actual behavior**

Quite many regions have no names and some tests have no javadocs

**Visual proofs (screenshots, logs, images)**

Here is one of generated test:
```java
public class SortTest {
    ///region Test suites for executable org.example.Sort.arrayCopy

    ///region

    @Test
    public void testArrayCopy1() {
        Sort sort = new Sort();

        int[] actual = sort.arrayCopy();

        int[] expected = {1, 2, 3};
        assertArrayEquals(expected, actual);
    }

...
```

**Comment by amandelpie** [comment]
@tyuldashev the default behaviour - do not generate summaries/regions if something goes wrong (it should be logged by logger.error to the log). We are not guarantee at this moment that all tests will have regions and other summaries.

Sometimes it's a developer bug in summaries, sometimes it's the limitation of summaries functionality.

I suggest or copy the reason of crash from logs (if it's the same it's one bug if is different—there are a few bugs) or copy generated results (with missed summaries)

**Comment by amandelpie** [comment]
On my laptop looks like it's reproduced and related to the problem #1227

**Comment by amandelpie** [comment]
@tyuldashev @alisevych Looks like it was fixed by #1227 closed earlier, it's not reproduced on my side

**Comment by amandelpie** [comment]
@tyuldashev @alisevych please reproduce and close, the bug is not reproduced on the master and closed earlier

For example, the following test is generated

```
public final class SortTest {
    ///region Test suites for executable custom.Sort.arrayCopy

    ///region FUZZER: SUCCESSFUL EXECUTIONS for method arrayCopy()

    /**
     * @utbot.classUnderTest {@link Sort}
     * @utbot.methodUnderTest {@link Sort#arrayCopy()}
     */
    @Test
    @DisplayName("arrayCopy: arg_0 = Sort()")
    public void testArrayCopy() {
        Sort sort = new Sort();

        int[] actual = sort.arrayCopy();

        int[] expected = {1, 2, 3};
        assertArrayEquals(expected, actual);
    }
    ///endregion

    ///endregion
}

```

**Comment by tyuldashev** [comment]
@amandelpie yes, looks like this one fixed, there is one question though: should region have name even when `Summaries generation` is **Disabled**? In latter case region name still could be empty.

**Comment by tyuldashev** [comment]
Per discussion, that's okay that region name is empty when summaries disabled in the settings. So closing the case as fixed.
