### ISSUE TITLE
IDEA hangs during test generation

### ISSUE THREAD

**Issue by tyuldashev** [UnitTestBot/UTBotJava#1207]
**Description**

I've faced the problem that IDEA becomes not responsible during several test generations with the latest RC builds. While it's most probably caused by insufficient memory allocated to IDEA, UTBot test generation should not cause hang of IDEA without ability to cancel test generation process.

**To Reproduce**

Most of the times I've faced that problem after the following steps:
1. Open UTBot project
2. Generate tests for [org.utbot.examples.algorithms.Sort](https://github.com/UnitTestBot/UTBotJava/blob/main/utbot-sample/src/main/java/org/utbot/examples/algorithms/Sort.java)

**Expected behavior**

Tests are generated

**Actual behavior**

Test generation started but in a about a minute IDEA stops to respond to user interaction. Once it finished generation in about 17min, but latter hanged again. Other times I killed IDEA after waiting for several minutes. 

**Visual proofs (screenshots, logs, images)**

[Thread dumps](https://github.com/UnitTestBot/UTBotJava/files/9836531/log.zip)

**Environment**
IDEA 2022.1.4, with default `-Xmx2022m` in VM settings
UTBot - [utbot-intellij-2022.10.459 - build from unittestbot/rc10192022](https://github.com/UnitTestBot/UTBotJava/actions/runs/3281195826)

**Additional information**
Increasing IDEA memory to 4Gb seems resolves the problem. But I believe UTBot still should not cause hangs in IDEA and still be cancelable.

**Comment by alisevych** [comment]
**Additional details**

Same happened to me once - on IDEA 2022.2.3
IDE hanged after test generation had already finished - and some imports and build project were being made.
It hanged for about 16 hours and only kill process helped.

**Comment by tyuldashev** [comment]
That seems caused by #1225. If we try to open such file in IDEA it would warn that this file is too big and would skip formatting and analyzing it. We may implement similar or the same check, to prevent such problem.

**Comment by tyuldashev** [comment]
Tested with build from main branch [#483](https://github.com/UnitTestBot/UTBotJava/actions/runs/3334948288)
IDEA 2022.1.4 & 2022.2.3
