### ISSUE TITLE
Too many tests generated by Fuzzer

### ISSUE THREAD

**Issue by tyuldashev** [UnitTestBot/UTBotJava#1225]
**Description**

Sometimes fuzzer generates a lot of tests, which are not reduced for some reason by minimizer which result in inresponsible IDE.

**To Reproduce**

1. Open Java UTBot project
2. Set `Test generation method` to 100% `Fuzzing`
3. Generate tests for `org.utbot.examples.algorithms.Sort`

**Expected behavior**

Reasonable amount of files generated.

**Actual behavior**

Result test file is about 17Mb and seems contains thousands of tests. This cause problem for formatting and analysis this file in IDEA (see #1207)

**Visual proofs (screenshots, logs, images)**

Attaching generated file - [SortTest.zip](https://github.com/UnitTestBot/UTBotJava/files/9853234/SortTest.zip)

**Comment by Markoutte** [comment]
Reproducible if project has a space character in the full path.

**Comment by tyuldashev** [comment]
Tested with build from main branch [#483](https://github.com/UnitTestBot/UTBotJava/actions/runs/3334948288)
IDEA 2022.1.4 & 2022.2.3
