### ISSUE TITLE
Summaries are not generated due to FileNotFoundException 

### ISSUE THREAD

**Issue by amandelpie** [UnitTestBot/UTBotJava#1227]
**Description**

Summaries are not generated due to FileNotFoundException  thrown in the [SourceCodeParser.kt:45](https://github.com/UnitTestBot/UTBotJava/blob/main/utbot-summary/src/main/kotlin/org/utbot/summary/ast/SourceCodeParser.kt#L45)

The error message is the following: "C:\Users\<username>\.jdks\corretto-11.0.16.1\lib\src.zip!\java.base\java\lang\Math.java (??????? ?? ??????? ????? ????????? ????)"

Need to say that the Math.java file is exist as a Zip entry in the archive with sources mentioned above

**To Reproduce**

1. Run runIde Gradle task
2. Copy to the open project the mentioned below snippet of code
3. Use plugin to generate tests for DoubleFunctions::hypo method

```
public class DoubleFunctions {
    public double hypo(double a, double b) {
        return Math.sqrt(Math.pow(a, 2) + Math.pow(b, 2));
    }

    @SuppressWarnings("ManualMinMaxCalculation")
    public double max(double a, double b) {
        return a > b ? a : b;
    }

    public double circleSquare(double r) {
        if (r < 0 || Double.isNaN(r) || r > 10000) {
            throw new IllegalArgumentException();
        }
        double square = Math.PI * r * r;
        if (square > 777.85) {
            return square;
        } else {
            return 0;
        }
    }

    public int numberOfRootsInSquareFunction(double a, double b, double c) {

        double result = b * b - 4 * a * c;
        if (result > 0) {
            return 2;
        } else if (result == 0) {
            return 1;
        }
        return 0;
    }
}
```

**Expected behavior**

Tests with summaries should be generated.

**Actual behavior**

Tests are generated without summaries.

**Visual proofs (screenshots, logs, images)**

![image](https://user-images.githubusercontent.com/105506115/197727862-331b8739-98fa-4896-97ce-ef05427392a4.png)

**Environment**

The Coretto jdk 11.0.16.1 is installed and used in both, initial and debug IDEs

**Comment by amandelpie** [comment]
Is not reproduced on other machines by other community members

**Comment by alisevych** [comment]
@amandelpie Same for me - not reproducing.
Probably the exact JDK files have been corrupted somehow.

**Comment by amandelpie** [comment]
Looks like the problem was related to the wrong JAVA_HOME and PATH environment variables.
I installed alternative JDK, set up env vars correctly and it's not reproduced.

**Comment by amandelpie** [comment]
It's reproduced on two different machines with Windows 10 / IDEA 2022.1.2 and 2022.2.2

The main problem, that src.zip/blabla is not a file, it's a Zip entry and Java File API could not recognized it as a File.
