### ISSUE TITLE
TestNG 7.5 should be added to Maven project with JDK 8

### ISSUE THREAD

**Issue by alisevych** [UnitTestBot/UTBotJava#1251]
**Description**

TestNG RELEASE version is added to dependencies in Maven project with JDK 8

**To Reproduce**

1. Install a plugin build from main, [as an example](https://github.com/UnitTestBot/UTBotJava/actions/runs/3335687327) in IntelliJ Idea
2. Create Maven project with JDK 8
3. Add sample code to it
4. Open Generate Tests with UnitTestBot... and select TestNG to be installed
5. Generate Tests
6. Check pom.xml

**Expected behavior**

Project JDK 8 requires TestNG 7.5 to be defined in pom.xml

**Actual behavior**

RELEASE version is added

**Visual proofs (screenshots, logs, images)**

~~~
        <dependency>
            <groupId>org.testng</groupId>
            <artifactId>testng</artifactId>
            <version>RELEASE</version>
            <scope>test</scope>
        </dependency>
~~~

**Environment**

Windows 10 Pro
IDEA 2022.1.4 / 2022.2.3

**Additional context**

Probably it is related to unavailability of maven repositories - but other dependencies are added normally.

**Comment by EgorkaKulikov** [comment]
@sofurihafe and me investigated that the reason is a bug in `MavenProjectModelModifier`

Not sure that it is easy to fix. See https://intellij-support.jetbrains.com/hc/en-us/community/posts/8751639094930-Inherit-from-MavenProjectModelModifier for more details.
