### ISSUE TITLE
`UtUtils.deepEquals` not resolved in generated tests

### ISSUE THREAD

**Issue by tyuldashev** [UnitTestBot/UTBotJava#1255]
**Description**

In case user code contains modification of collections UTBot tries to verify it with `UtUtils.deepEquals` method but it cannot be resolved in tests, so they cannot be compiled and executed.

**To Reproduce**

1. In UTBot settings set `Generated test language` to `Kotlin`
2. Generate tests for following code
```kotlin
class Listing {
    val list = mutableListOf<String>()
    fun addValue(str:String): List<String> {
        list.add(str)
        return list
    }
}
```

**Expected behavior**

Compilable tests are supposed to be generated.

**Actual behavior**

Generated tests are red and can not be run
```kotlin
import org.utbot.runtime.utils.UtUtils.deepEquals
import org.junit.jupiter.api.Assertions.assertTrue

class PersonTest {
    ///region Test suites for executable examples.introduction.Person.likes
    
    ///region
    
    /**
    @utbot.classUnderTest {@link examples.introduction.Person}
 * @utbot.methodUnderTest {@link examples.introduction.Person#likes(examples.introduction.Person)}
 *  */
    @Test
    @DisplayName("likes: other = Person(String)")
    fun testLikes() {
        val person = Person("")
        val other = Person("")
        
        val actual = (person.likes(other) as ArrayList)
        
        val expected = ArrayList()
        expected.add(other)
        assertTrue(deepEquals(expected, actual))
    }
...
```

**Visual proofs (screenshots, logs, images)**

![image](https://user-images.githubusercontent.com/10035839/198589768-3aaf5cde-b563-49d4-a83b-d5c01d76bbef.png)

**Additional context**

I assume that problem with `ArrayList()` is part of #88, so doesn't describe it here

**Comment by volivan239** [comment]
I believe that currently all methods put to `UtUtils.kt` are not resolved. Working on that

**Comment by tyuldashev** [comment]
Probably duplicate of #1080 then
