### ISSUE TITLE
No suitable method found for assertArrayEquals

### ISSUE THREAD

**Issue by CaelmBleidd** [UnitTestBot/UTBotJava#1274]
**Description**

We still have an error `No suitable method found for assertArrayEquals(boolean[], boolean[]` that leads us to generating uncompilable code. 

**To Reproduce**

1. Run the ContestEstimator on `guava-26` project, `Booleans` class
2. Look at the results

**Expected behavior**

Successfully generated and compilable tests.

**Actual behavior**

Compilation errors

**Visual proofs (screenshots, logs, images)**

![image](https://user-images.githubusercontent.com/31047452/199141699-d1f2f5d8-0289-4334-9607-39953de40e79.png)

**Environment**

Default contestEstimator environment, 120s timeout

**Additional context**

This issue is related to [PR464](https://github.com/UnitTestBot/UTBotJava/pull/464)

**Comment by EgorkaKulikov** [comment]
Actually this is a problem of `ContestEstimator`, not code generator. 
We need to have JUnit version 4.12 or higher to generate tests with asserts on Boolean arrays. This requirement is fulfilled in plugin. In estimator it is correct sometimes... We try to install JUnit 4.13.2 in Gradle script.

However, guava-26 contains JUnit 4.11 jar in it's dependencies. In current implementation this jar is added to classpath and is considered more preferable than installed via Gradle dependency with the correct version.

To conclude, this problem requires some improvements in dependencies processing in`ContestEstimator`.
