### ISSUE TITLE
Do not suggest to test Kotlin protected methods

### ISSUE THREAD

**Issue by tyuldashev** [UnitTestBot/UTBotJava#1280]
**Description**

UTBot suggests to generate tests for `protected` members of Kotlin class, but because they are visible only inside that class itself and its descendants the generated code cannot access such methods and fails at compilation.

**To Reproduce**

1. In UTBot settings set `Generated test language` to `Kotlin`
2. Invoke test generation for following class
```kotlin
class Calc {
    protected fun substract(a: Int, b: Int): Int {
        return a - b
    }
}
```

**Expected behavior**

UTBot either warn that there is NO methods it can test or create compilable code (if we can and want to access this method through reflection).

**Actual behavior**
UTBot allows to generate tests for that method and create uncompilable code.

**Visual proofs (screenshots, logs, images)**

![image](https://user-images.githubusercontent.com/10035839/199236428-c38fd27e-b24e-473e-967d-6e07df3a7d2f.png)

![image](https://user-images.githubusercontent.com/10035839/199237232-3932ef62-6bec-44d7-9726-b431d7064dcf.png)

**Comment by EgorkaKulikov** [comment]
In current implementation we consider protected keyword in terms of Java.
May be we should improve `PsiClassHelper.filterTestableMethods`. Or suggest some more complicated separation between two protected terms.
