### ISSUE TITLE
Kotlin. Members list contains class and file when package-level const are used

### ISSUE THREAD

**Issue by alisevych** [UnitTestBot/UTBotJava#1281]
**Description**

Kotlin file contains one class with the same name.
There are const variables in the same file - outside the class. But there are no functions on package level.
Members list on UnitTestBot dialog contains the class and the file with same name separately.
Removing const variables result in main() function in members list only.

**To Reproduce**

1. Install [the latest UnitTestBot plugin build from main](https://github.com/UnitTestBot/UTBotJava/actions/runs/3367468745) in IntelliJ Idea 2022.2.3 (latest)
2. Create a Gradle project with Kotlin support
3. Create a package in src/main/kotlin sources root
4. Add the following code to a Kotlin file PrintString.kt

```kotlin
package ort.utbot.examples.strings

const val question = "life, the universe, and everything"

class PrintString {

    fun main() {
        println(question)
    }
}
```

5. Press Alt+Shift+U on the file in Project view (or using context menu on the file)

**Expected behavior**

There should be only functions in Member list on the dialog.

**Actual behavior**

There are the class and the file names separately.

**Visual proofs (screenshots, logs, images)**

![image](https://user-images.githubusercontent.com/37301492/199243649-3640e738-a471-4d32-a70c-d709917fb4cd.png)

**Environment**

Windows 10 Pro
IntelliJ IDEA 2022.2.3 (same on 2022.1.4)
Gradle project, JDK 11
kotlin 221-1.7.20-release-201-IJ5591.52

**Comment by volivan239** [comment]
I think this is the designed behavior. When we launch action from project view by clicking on file(s), all the classes produced by selected files appear in member list (including the classes with no methods as it may take long time to filter empty classes). In first example, the code produces 2 classes -- `PrintString` and a special "class-file" `PrintStringKt` which may contain top-level methods. When there are no top-level declarations, second class is not produced by the Kotlin compiler, therefore only one class is shown.

**Comment by alisevych** [comment]
Thank you, understood! Closing as not a bug.
