### ISSUE TITLE
Regions names for parameterized tests

### ISSUE THREAD

**Issue by alisevych** [UnitTestBot/UTBotJava#1301]
**Description**

Some tests generated for ArraysQuickSort.sort in Parameterized mode are presented as regular tests.
They are put in to region 
`///region Tests for method sort(int[], int, int, int[], int, int) that cannot be presented as parameterized`
Now there are 2 types of such tests:
- #1252 
- #1161 

**To Reproduce**

1. Install [latest build from main](https://github.com/UnitTestBot/UTBotJava/actions/runs/3377312923) into IDEA 2022.2.3
2. Check File -> Settings are default: 95% Symbolic execution 
3. Open UTBotJava project
4. Generate tests for `ArrayQuickSort` with JUnit5 and Parameterized on.

**Expected behavior**

Regions in the generated tests are supposed to be similar to the ones generated with parameterization off.

**Actual behavior**

`///region Tests for method sort(int[], int, int, int[], int, int) that cannot be presented as parameterized`

Regions in generated tests, that cannot be presented as parameterized, do not contain information about which suite they belong to.
Fuzzing / Symbolic, Successful / Explicitly thrown exceptions / ...

**Visual proofs (screenshots, logs, images)**

Regions for parameterized tests:
![image](https://user-images.githubusercontent.com/37301492/199696420-9ba278cb-7c20-4806-9aa2-8988d531fe3b.png)

Regions for regular tests:
![image](https://user-images.githubusercontent.com/37301492/199696224-b7f51f04-e215-48ab-8d8d-d99085a2fef7.png)

**Environment**

IntelliJ IDEA

**Comment by alisevych** [comment]
@korifey @amandelpie @EgorkaKulikov 
Could you please check the expected and actual result? What would be the correct way to name these suites?

**Comment by amandelpie** [comment]
@alisevych could we say now that we are satisfied for today with the existing master

**Comment by alisevych** [comment]
> @alisevych could we say now that we are satisfied for today with the existing master?

As for regions for parameterized tests - they are readable.
