### ISSUE TITLE
Test generation is not canceled when user tries to stop it at building phase

### ISSUE THREAD

**Issue by tyuldashev** [UnitTestBot/UTBotJava#1306]
**Description**

For big projects build phase could take noticeable amount of time if user tries to cancel test generation at the moment UBTot still proceeds with test generation.

**To Reproduce**

1. Open utbot project
2. Invoke test generation on some class, on `org.utbot.examples.strings.StringExamples` for example
3. Quickly click on cancel while UTBot still at building phase
![image](https://user-images.githubusercontent.com/10035839/199742778-cdeedc99-45f1-417a-ada8-b259fdf7d3c2.png)

**Expected behavior**

Generation of tests stopped

**Actual behavior**

UTBot stops (or try to stop building) but then procced with reading classes and test generation.

**Comment by Vassiliy-Kudryashov** [comment]
This issue duplicates #1100 and can be closed as obsolete (see revision [53c3b3f8](https://github.com/AbdullinAM/UTBotJava/commit/53c3b3f8))
