### ISSUE TITLE
Summaries disable in config file is not applied

### ISSUE THREAD

**Issue by alisevych** [UnitTestBot/UTBotJava#1321]
**Description**

`enableSummariesGeneration=false` is not applied to Java project from global config file `settings.properties`
Using plugin with:
 - #1298 

**To Reproduce**

1. Install [release build](https://github.com/UnitTestBot/UTBotJava/releases/tag/2022.11) into IDEA
2. Add `enableSummariesGeneration=false` to the global config file `~\.utbot\settings.properties`
3. Restart IDEA 2022.2.3 (latest) - to apply `settings.properties`
4. Create a new Java project (f.i. Maven project with JDK 11)
5. Check File -> Settings -> Tools -> UnitTestBot
6. Generate tests for a sample Java class

**Expected behavior**

5. Summaries are supposed to be turned off - as in global config.
6. Tests are supposed to be generated without Java docs, regions and desriptions.

**Actual behavior**

5. Summaries are enabled.
6. Summaries are generated - as it is default for Java project - with - #1283 

**Visual proofs (screenshots, logs, images)**

![image](https://user-images.githubusercontent.com/37301492/200360948-ec6272d4-303e-47a7-bbe6-20b8ce841b13.png)

```java
public final class MainTest {
    ///region Test suites for executable org.example.Main.main

    ///region FUZZER: SUCCESSFUL EXECUTIONS for method main(java.lang.String[])

    /**
     * @utbot.classUnderTest {@link Main}
     * @utbot.methodUnderTest {@link Main#main(String[])}
     */
    @Test
    @DisplayName("main: arg_0 = String[3]")
    public void testMainWithNonEmptyObjectArray() {
        String[] args = {"noimn", "oesjb", "noimn"};

        Main.main(args);
    }
    ///endregion

    ///endregion
}
```

_Originally posted by @alisevych in https://github.com/UnitTestBot/UTBotJava/issues/1291_

**Comment by amandelpie** [comment]
This is an area of undefined behavior.
As I see, we have no UI Settings fully synchronized with the UTSettings at this moment.

It's an open question, could we have erase the UI setting with the value from the file?

I could say, that at this moment we have no support for these settings to be synchronized with UI. UI could rule these settings and erase all result in this with its own value.

**Comment by alisevych** [comment]
@Vassiliy-Kudryashov 
Could you please take this issue? Need to find an appropriate solution how global and project settings should be connected.
