### ISSUE TITLE
Improper configuration of spring project	

### ISSUE THREAD

**Issue by alexeyfridman** [UnitTestBot/UTBotJava#133]
SAT-1658

Query rewriter default configuration leads to multiple issues with CE

**Comment by denis-fokin** [comment]
We will check it as soon as the Spring solutions are taken into account

**Comment by EgorkaKulikov** [comment]
@alexeyfridman Information in mentioned issue is not enough to reproduce the problem. Which project was analyzed, what was the class under test? How can I obtain it to reproduce? What were the settings of UtBot when analysis was run?

Please, provide more info or close the issue.
