### ISSUE TITLE
Reduce size of plugin zip

### ISSUE THREAD

**Issue by alisevych** [UnitTestBot/UTBotJava#1333]
**Description**

Plugin archive size increased after merging #1199. Need to reduce it below 100 MB.

**To Reproduce**

1. Open Actions -> Plugin and CLI: publish as archives -> open one of the last runs
2. Download this artifact
3. Check downloaded file size

**Expected behavior**

Plugin archive size should be below 100 MB.

**Actual behavior**

Plugin archive size is 111 MB.

**Visual proofs (screenshots, logs, images)**

![image](https://user-images.githubusercontent.com/37301492/200788659-2a79c0ff-8267-41a0-b223-acd19a05d6e1.png)

**Additional context**

Archive size on GitHub is calculated from unpacked JAR-files inside. Now it is 121 MB.

Before #1199 was merged the size of archive was 98 MB, 107 MB unpacked (shown on GitHub)

**Comment by tamarinvs19** [comment]
Current status: we found the main problem - it is `python3parser` package (more then 10Mb with dependenies) which we used to parse python code
Solution: change parser, size of the new parse is ~300Kb, now we are rewriting our code with python3parser

We plan to finish rewriting in January

**Comment by alisevych** [comment]
@tamarinvs19 Could you please check if `python3parser` is included in the current plugin build? As it is present in utbot-python module only. And currently the plugin is built without utbot-python and utbot-js.

**Comment by tamarinvs19** [comment]
The latest version 2022.11 does not contain `utbot-python` and so does not contain this module (zip size ~98Mb). Now we can remove python from build if we delete `IC` version from python versions in `gradle.properties` (example [here](https://github.com/UnitTestBot/UTBotJava/actions/runs/3590612791)). Without python build has size ~98Mb

**Comment by alisevych** [comment]
Sounds good, thank you!

**Comment by alisevych** [comment]
Fixed with
 - #1763
