### ISSUE TITLE
UtUtils has region without name

### ISSUE THREAD

**Issue by tyuldashev** [UnitTestBot/UTBotJava#1380]
**Description**

Not every `UtUtils` region has name.

**To Reproduce**

1. Open `utbot` project
2. Generate tests for `org.utbot.examples.collections.QueueUsages` class
3. Open generated `org.utbot.runtime.utils.java.UtUtils` file

**Expected behavior**
All regions have names

**Actual behavior**
The first region has no name

```java
...
/**
 * This is a regular UtUtils class (without mock framework usage)
 * UtUtils class version: 2.0
 */
public final class UtUtils {
    ///region

    /**
     * This class represents the {@code type} and {@code value} of a value captured by lambda.
     * Captured values are represented as arguments of a synthetic method that lambda is compiled into,
     * hence the name of the class.
     */
    public static class CapturedArgument {
        private Class<?> type;
        private Object value;

        public CapturedArgument(Class<?> type, Object value) {
            this.type = type;
            this.value = value;
        }
    }
    ///endregion
...
```

**Additional context**

That seems quite old issue, not related to recent changes.

**Comment by amandelpie** [comment]
@EgorkaKulikov I could help with the review
