### ISSUE TITLE
Region descriptions are rendered as JavaDocs. Could we do better?

### ISSUE THREAD

**Issue by alisevych** [UnitTestBot/UTBotJava#1404]
**Description**

Not rendering region description are being generated for Enum tests.

**To Reproduce**

1. Run the 'lrs' project in IntelliJ Idea
2. Install [one of the latest plugin builds](https://github.com/UnitTestBot/UTBotJava/actions/runs/3514234169) from main into IDEA
3. Summaries are on, default type is chosen - with Java docs tags
4. Generate tests for `LongRangeType`
5. Open the generated test
6. Do the same for Plain text summaries

**Expected behavior**

Region descriptions can be rendered and links are resolved.

**Actual behavior**

Region description is formatted with `///` and stays as plain text when Java docs are rendered.

**Visual proofs (screenshots, logs, images)**

![image](https://user-images.githubusercontent.com/37301492/203068047-d93e05d3-abf9-4cff-a89d-6be032bccafd.png)

![image](https://user-images.githubusercontent.com/37301492/203068061-616eebb9-c2d8-4f71-9ff8-b7abb7b8aae8.png)

**Environment**

Windows 10 Pro
IntelliJ IDEA 2022.2.3 (Latest)

**Comment by amandelpie** [comment]
We need to discuss what's better
```
    /// Common steps:
    /// 
    /// Tests execute conditions:
    ///      (myBytes == 8): False
    /// invoke:
    ///     com.intellij.codeInspection.dataFlow.rangeSet.LongRangeType#min() once
    /// return from: return diff < min() || diff > max();

```

or

```
    ///region SYMBOLIC EXECUTION: SUCCESSFUL EXECUTIONS #1 for method subtractionMayOverflow(long, long)
    /// 
    /// Common steps:
    /// <pre>
    /// Tests execute conditions:
    ///     {@code (myBytes == 8): False}
    /// invoke:
    ///     {@link com.intellij.codeInspection.dataFlow.rangeSet.LongRangeType#min()} once
    /// return from: {@code return diff < min() || diff > max();}
    /// </pre>
```

**Comment by amandelpie** [comment]
After fast research, it became clear that it involves the changing of rendering different CgElements and so on.
And as a result, we should support two cases of rendering in the package of code related to CgElements or move this functionality to summaries. This is why I decided to leave it in the existing state.

@EgorkaKulikov @alisevych @olganaumenko you need to decide
