### ISSUE TITLE
The rendering of some parts in plain JavaDocs is broken

### ISSUE THREAD

**Issue by amandelpie** [UnitTestBot/UTBotJava#1430]
**Description**

After the [commit ](https://github.com/UnitTestBot/UTBotJava/commit/04c85da1878f4b8ab1fb6d2bc50fa9e06eef6495) the rendering of generated JavaDocs was broken (some \n were missed as I see)

Looks like this change broke this` utbot-framework/src/main/kotlin/org/utbot/framework/codegen/renderer/CgAbstractRenderer.kt:363`

Please check the changes in rendering with some simple manual tests for Summaries generation

The ticket is related to the #1404, ask @alisevych for the test project, but I'm sure that you will obtain the same result on any piece of code from our samples

**To Reproduce**

1. Run the 'lrs' project in IntelliJ Idea
2. Run `runIde`
3. Go to UtBot settings
4. Summaries are on, default type is chosen—with plain Java docs tags (not custom tags)
5. Generate tests for LongRangeType
6. Open the generated test
7. See wrong formatting.

**Expected behavior**

```
 /**
     * <pre>
     * Test  returns from: {@code return diff < min() || diff > max(); } 
     * </pre>
     */
    @Test
    @DisplayName("subtractionMayOverflow: return diff < min() || diff > max() : False -> return diff < min() || diff > max()")
    public void testSubtractionMayOverflow_DiffGreaterOrEqualMinOrDiffLessOrEqualMax() {
        LongRangeType longRangeType = LongRangeType.INT32;

        boolean actual = longRangeType.subtractionMayOverflow(128L, 256L);

        assertFalse(actual);
    }

```
**Actual behavior**

```
 /**
     * <pre>
     * Test  * returns from: {@code return diff < min() || diff > max(); } *
     * </pre>
     */
    @Test
    @DisplayName("subtractionMayOverflow: return diff < min() || diff > max() : False -> return diff < min() || diff > max()")
    public void testSubtractionMayOverflow_DiffGreaterOrEqualMinOrDiffLessOrEqualMax() {
        LongRangeType longRangeType = LongRangeType.INT32;

        boolean actual = longRangeType.subtractionMayOverflow(128L, 256L);

        assertFalse(actual);
    }

```

**Additional context**

Before the mentioned commit all works correctly

**Comment by amandelpie** [comment]
@sofurihafe please have a look at this ticket, if it's possible for you

**Comment by EgorkaKulikov** [comment]
It seems that we could not apply our changes in the rendering of `CgDocRegularStatement` because a regression in summaries happened. Instead of it, we should introduce new Codegen item `CgDocLineStatement` for the goals of UtUtils.

**Comment by amandelpie** [comment]
I've tested it, now it works properly
