### ISSUE TITLE
Unused import in the generated test

### ISSUE THREAD

**Issue by alisevych** [UnitTestBot/UTBotJava#1449]
**Description**

There is an unused import in the generated test:
`import java.net.UnknownHostException;`
for the code containing `Socket.connect`

**To Reproduce**

1. Install [Build from the main branch, one used]() into IDEA 2022.2.3
2. Open UTBotJava project
3. Check File -> Settings are default: 95% Symbolic execution 
4. Generate tests for the following class:

```java
public class SecurityCheck {
    public int connect(Socket socket) throws IOException {
        socket.connect(new InetSocketAddress("0.0.0.0", 22));
        return 0;
    }
}
```

**Expected behavior**

Only required imports are added to the generated test class.

**Actual behavior**

There is unused `import java.net.UnknownHostException;`

**Visual proofs (screenshots, logs, images)**

![image](https://user-images.githubusercontent.com/37301492/205069051-349979de-bdbb-4558-98c8-4093d10e7898.png)

**Environment**

Windows 10 Pro
IntelliJ IDEA 2022.2.3 (JBR 17)
Gradle 
JDK 11

**Additional context**

_Originally posted by @alisevych in https://github.com/UnitTestBot/UTBotJava/issues/1314#issuecomment-1316870194_

**Comment by EgorkaKulikov** [comment]
Can't reporoduce this this bug (both @sofurihafe and me), however, a new issue was discovered https://github.com/UnitTestBot/UTBotJava/issues/1590
