### ISSUE TITLE
Plugin is not compatible with IntelliJ IDE 2022.3

### ISSUE THREAD

**Issue by alisevych** [UnitTestBot/UTBotJava#1466]
**Description**

UnitTestBot cannot be installed into the latest IDE: IDEA, PyCharm, WebStorm, because it has limitation up to 222.* version.
Latest PyCharm 2022.3 has 223.7571.203 version (came out on Dec 1)
Same for latest WebStorm 2022.3 (Nov 28)
Same for IDEA (Nov 30)

**To Reproduce**

1. [Download and install latest PyCharm Community](https://www.jetbrains.com/pycharm/download/#section=windows)
2. Download one of the latest plugin builds from main
3. File > Settings > Plugins > Install from disk > select downloaded UnitTestBot

**Expected behavior**

UnitTestBot is supposed to be installed.

**Actual behavior**

Error message that UnitTestBot is not compatible with this IDE version

**Visual proofs (screenshots, logs, images)**

![image](https://user-images.githubusercontent.com/37301492/206114313-876cb79c-8862-40ce-a329-9578f621c496.png)

`Plugin 'UnitTestBot' (version '2022.12.576.') is not compatible with the current version of the IDE, because it requires build 222.* or older but the current build is PC-223.7571.203`

**Environment**

Windows 10 Pro
IntelliJ PyCharm Community 2022.3 / IDEA / WebStorm

**Comment by denis-fokin** [comment]
There is no kotlin distributable that we can use for the latest version. Will wait for the next release.

**Comment by Vassiliy-Kudryashov** [comment]
Unfortunately, the last abailable version is [222-1.7.21-release-272-IJ4167.29](https://cache-redirector.jetbrains.com/plugins.jetbrains.com/maven/com/jetbrains/plugins/org.jetbrains.kotlin/222-1.7.21-release-272-IJ4167.29/org.jetbrains.kotlin-222-1.7.21-release-272-IJ4167.29.pom )

**Comment by alisevych** [comment]
After this bug is fixed - also check rendering custom Java docs in newest IDE.

**Comment by alisevych** [comment]
I've tried to install plugin built from today's main - the same error:

![image](https://user-images.githubusercontent.com/37301492/221869567-5dedfdb0-f046-4a0f-8435-9ae70dd8794c.png)

**Comment by alisevych** [comment]
Kotlin plugin last released version is still 222.
There is only EAP version compatible with IDEA 2022.3: https://plugins.jetbrains.com/plugin/6954-kotlin/versions/eap

**Comment by alisevych** [comment]
But in IDEA Ultimate 2022.3.2 there is bundled Kotlin plugin version 223-*

![image](https://user-images.githubusercontent.com/37301492/221874720-3cd8a1e9-d4d3-4661-8413-31d3248f1ba8.png)
