### ISSUE TITLE
Python test generation error

### ISSUE THREAD

**Issue by alisevych** [UnitTestBot/UTBotJava#1478]
**Description**

Python test generation error is showing for quite simple python functions, including examples on [utbot.org](https://www.utbot.org/demo/?language=Python)

**To Reproduce**

1. Install [one of the latest plugin builds from main ](https://github.com/UnitTestBot/UTBotJava/actions/runs/3637743780) in IntelliJ Idea 2022.2.3
2. Install Python plugin from MarketPlace
3. Create a Python project 
4. Add the following code to it:

```python
def print_hi(name):
    # Use a breakpoint in the code line below to debug your script.
    print(f'Hi, {name}')  # Press Ctrl+F8 to toggle the breakpoint.

def div(a, b):
    return a / b

# Press the green button in the gutter to run the script.
if __name__ == '__main__':
    print_hi('PyCharm')
```
5. Press Alt+Shift+U in code
6. Select both functions and generate tests
7. Agree to install suggested requirements
8. Make 5-6 steps once again

**Expected behavior**

Tests are supposed to be generated.

**Actual behavior**

An error dialog is show with the following test:
`Cannot create tests for the following functions: print_hi, div`

**Visual proofs (screenshots, logs, images)**

![image](https://user-images.githubusercontent.com/37301492/206162802-f31501c3-b709-4cb3-a97a-f679bf8a9917.png)

**Environment**

Windows 10 Pro
IntelliJ IDEA 2022.2.3 (not latest)

**Additional context**

Same with `pytest` or increased timeouts or manually create test sources root.
`Generating tests...` is displayed in inline progress.

**Comment by tamarinvs19** [comment]
OK, I reproduced this bug. It happens only at the first plugin run. If I restart IDEA after creating python project, I can generate tests
