### ISSUE TITLE
Python test generation UI action is unavailable in IC

### ISSUE THREAD

**Issue by tamarinvs19** [UnitTestBot/UTBotJava#1554]
**Description**

After PR #1545 I cannot run UtBot Python plugin in IntelliJ Community.

In file `UTBotJava/utbot-intellij/src/main/kotlin/org/utbot/intellij/plugin/ui/actions/GenerateTestAction.kt`:
```kotlin
if (languageAssistant == null || !accessByProjectSettings(e)) {
    e.presentation.isEnabled = false
} else {
    languageAssistant.update(e)
}
```
in IC and in python project the second condition is true, but we need to call `PythonLanguageAssistant.update(e)`.

**To Reproduce**

1. Run the python project in IntelliJ Idea Community
2. Try to use plugin to generate tests for python file

**Expected behavior**

UI action with python settings

**Actual behavior**

I cannot generate tests for python file

**Visual proofs (screenshots, logs, images)**

![image](https://user-images.githubusercontent.com/23080942/208472004-6478c089-15f7-4b4a-9c72-b40bba3aa704.png)

**Environment**

**Additional context**

**Comment by rudolf101** [comment]
@tamarinvs19 Open IDEA settings -> UnitTestBot Plugin -> Enable Experimental Language Support
