### ISSUE TITLE
UtBot mocks interface even when `Do not mock` is selected

### ISSUE THREAD

**Issue by tyuldashev** [UnitTestBot/UTBotJava#1560]
**Description**
UtBot tries to mock parameter which type is interface without existing implementations. As `Do not mock` selected no Mockito dependencies are added and so generated code cannot be executed.

**To Reproduce**

1. Open some test project which has NO Mockito dependencies in it
2. Generate tests for code below, select `Do not mock` option

```java
public class CommonMocksExample {
    public Object mockInterfaceWithoutImplementors(InterfaceWithoutImplementors value) {
        return value.visit(this);
    }

}

interface InterfaceWithoutImplementors {
    Object visit(Object value);
}
```

**Expected behavior**

Generated tests have no mocks and can be executed. Or no tests are generated.

**Actual behavior**

Generated tests shown below. It contains references to Mockito `when` and `actual`, but because there is no Mockito dependency in the project, such tests cannot be executed.

```java
    @Test
    @DisplayName("mockInterfaceWithoutImplementors: InterfaceWithoutImplementorsVisit -> return value.visit(this)")
    public void testMockInterfaceWithoutImplementors_InterfaceWithoutImplementorsVisit() {
        CommonMocksExample commonMocksExample = new CommonMocksExample();
        InterfaceWithoutImplementors valueMock = mock(InterfaceWithoutImplementors.class);
        (when(valueMock.visit(any()))).thenReturn(null);

        Object actual = commonMocksExample.mockInterfaceWithoutImplementors(valueMock);

        assertNull(actual);
    }
```

**Visual proofs (screenshots, logs, images)**
![image](https://user-images.githubusercontent.com/10035839/208697991-e10645c4-6d35-4c3f-981f-71cc2188d591.png)

**Environment**
IDEA 2022.2.3
UTBot 2022.12.637 from unit-test-bot/rc16122022 branch

**Additional context**

That seems quite old bug, as it's reproducible in 2022.10.580 version of UTBot too.

**Comment by tyuldashev** [comment]
@CaelmBleidd Do you think some simple fix is possible here? Or the fix would definitely require significant amount of instigation/work?

Regarding expected result: in case we have to mock in this situation then we need to add dependency to avoid red code.

**Comment by CaelmBleidd** [comment]
No, I believe, it requires either a little work or no work at all. We have a similar mechanism for so-called `force mocking`, implemented inside `org.utbot.engine.util.mockListeners.MockListenerController` and `org.utbot.engine.util.mockListeners.MockListener` with its inheritors. AFAIR, it removes executions from the final set if they touched something that requires Mockito during the analysis. 

Probably, it'd be enough to just add in the `org.utbot.engine.Mocker#forceMock` function a similar code from the `org.utbot.engine.Mocker#shouldMock`.

@EgorkaKulikov please, take a look at it. Am I right that it is enough to solve the problem?
