### ISSUE TITLE
Remember selection of dialog options for Python test generation

### ISSUE THREAD

**Issue by tyuldashev** [UnitTestBot/UTBotJava#1563]
**Description**
When user selects for example non default Test framework during test generation for Python then next time it's reset to default value. The same with other fields, with exception of 'Test source root'

**To Reproduce**

1. Open Python project
2. Invoke test generation dialog
3. Select `Test framework = pytest`
4. Generate tests
5. Invoke the dialog again

**Expected behavior**

`pytest` test framework is preserved

**Actual behavior**

test framework is `Unittest` again

![image](https://user-images.githubusercontent.com/10035839/208937514-4593e571-39ac-4a02-8634-e0ba56607962.png)

**Additional context**

The same is with both timeouts and 'Visit only specified source'

**Comment by tyuldashev** [comment]
@tamarinvs19 please consult with @Vassiliy-Kudryashov about this one, this seems common problem with our dialogs and probably should be handled in some organized effort.

**Comment by tamarinvs19** [comment]
I found problem with a settings loading process from file: we cannot parse python test framework names (Unittest and pytest) from file and got error.

**Comment by tamarinvs19** [comment]
Done #2252
