### ISSUE TITLE
Identical `@DisplayName` for tests on enum methods

### ISSUE THREAD

**Issue by tyuldashev** [UnitTestBot/UTBotJava#1588]
**Description**

When UTBot generates tests for Enum methods then generated test methods have identical names with just method name - `@DisplayName("findStateByCode: ")`

**To Reproduce**

1. Open `utbot` project
2. Generate tests for `org.utbot.examples.enums.State`
3. Open the generated test

**Expected behavior**

Tests names are different and meaningful

**Actual behavior**

Methods names are like `testFindStateByCode_1` and `@DisplayName("findStateByCode: ")`

**Visual proofs**
![image](https://user-images.githubusercontent.com/10035839/209539273-69dc20f0-7a3d-4e78-ac1a-50d14e7f8150.png)

**Comment by amandelpie** [comment]
Very strange behaviour of the summaries module: @tyuldashev  need to add information to the initial settings - for example percentage of fuzzing value and so on. But if I remember correctly, the enums has very limited support in summaries and not only in summaries

**Comment by amandelpie** [comment]
@EgorkaKulikov I suppose it should be repoduced before fixing the bug, probably UTResult and UTExecutions contains zero useful information for generation in case of symbolic execution or fuzzing execution (see FuzzedMethodDescriptions)

**Comment by tyuldashev** [comment]
Nothing special, still reproducible with default settings:
![image](https://user-images.githubusercontent.com/10035839/214250388-f64dbb52-4727-4fa3-847b-4dd1d6333434.png)
