### ISSUE TITLE
'ByFuzzer' at the end of the test method generated by engine

### ISSUE THREAD

**Issue by tyuldashev** [UnitTestBot/UTBotJava#1666]
Branch: `andrey-t/summarization_in_contest_estimator`

**Description**
Some test methods created by UTBot have suffix `ByFuzzer` even though it's generated by symbolic engine. Per @Markoutte we should just get rid of this suffix completely.

**To Reproduce**

1. Open utbot project
2. Set filters for contestestimator in `org.utbot.contest.ContestEstimatorKt#main`
```java
       methodFilter = "com.google.common.collect.ReverseOrdering.*"
       projectFilter = listOf("guava-26.0")
```
3. Disable fuzzer: `val fuzzingRatio = 0.0`
4. Run contest estimator

**Expected behavior**

No tests named after fuzzer

**Actual behavior**
At least one of the test has `ByFuzzer` suffix
```java
@Test
    public void testMaxByFuzzer() throws Exception  {
...
```

**Comment by EgorkaKulikov** [comment]
Note that a branch with summarization support in ContestEstimator was merged into `main` right now.

The problem is highly likely located in `generateSummariesForTestsProducedBySymbolicExecutorWithoutSources` method, I just copypasted something from Fuzzer.
