### ISSUE TITLE
`UtExecutionInstrumentation` does not respect timeout in concrete execution

### ISSUE THREAD

**Issue by Domonion** [UnitTestBot/UTBotJava#1726]
**Description**

Currently `UtExecutionInstrumentation` measures only concrete execution, but not model construction for parameters and execution result.

Sometimes model construction might take too much time and will hang Instrumentation process indefenitely. This occurs too often in Contest Estimator, but problem relates to plugin too.

**To Reproduce**

1. In `ContestEstimator.kt` set:
      - set `javaHome`  to JDK8
      - `timeLimit=120`
      - `projectFilter = listOf("guava-26.0")`
      - set `utbot-junit-contest/src/main/resources/classes/guava-26.0/list` to
      ```
      com.google.common.primitives.Booleans
      com.google.common.primitives.Shorts
      ```
2. Start `ContestEstimator`
3. Tests for class `Shorts` once in a 2-3 generations will not be generated at all

**Expected behavior**

Everything works

**Actual behavior**

Tests for `Short` does not generate, Instrumentation process hangs on some requrest.

**Comment by alisevych** [comment]
Connected issue:
- #1718

**Comment by Domonion** [comment]
[possible.patch.txt](https://github.com/UnitTestBot/UTBotJava/files/10466946/possible.patch.txt)
Possible patch, verification required
