### ISSUE TITLE
Replacing fuzzer dependency for JS, Python and Go modules

### ISSUE THREAD

**Issue by rudolf101** [UnitTestBot/UTBotJava#1792]
**Description**

The JS, Python, and Go modules currently depend on `api(project(":utbot-fuzzers"))`. Looks like this dependency should be replaces to `implementation(project(":utbot-fuzzing"))`. In the future the better option is to get rid of all utbot-fuzzer module's classes. 

It is assumed that utbot-fuzzers will be modified and used only for Java/Kotlin

**Expected behavior**

The utbot-js, utbot-python and utbot-go modules depend on `implementation(project(":utbot-fuzzing"))` and do not contain imports from `org.utbot.fuzzer`

**Context**

Much of the `utbot-fuzzers` module is specific to Java, for the most part, the JS, Python and Go modules use only `FuzzedValue` and `UtFuzzedExecution`.

**Comment by tyuldashev** [comment]
@tamarinvs19 Anything else is planned here or we can close the case?

**Comment by rudolf101** [comment]
`utbot-js` still contains imports from `utbot-fuzzer`
