### ISSUE TITLE
Timeout exception (internal of UtBot) is dispayed in Summaries

### ISSUE THREAD

**Issue by EgorkaKulikov** [UnitTestBot/UTBotJava#1832]
**Description**

Timeout exception (internal of UtBot) is added to Java docs.
Tag @utbot.throwsException should be used for exceptions from user code only.

**To Reproduce**

Generate tests for the following code:

```java
public class A {

    public int hangForSeconds(int seconds) {
        for (int i = 0; i < seconds; i++) {
                Thread.sleep(1000);
        }
        return seconds;
    }
}
```

**Visual proofs (screenshots, logs, images)**

![image](https://user-images.githubusercontent.com/37301492/220297028-115becb1-8f13-4a92-a709-20d8b8e4ed84.png)

For example, the following summaries are generated:

```java
    /**
     * @utbot.classUnderTest {@link OrderService}
     * @utbot.methodUnderTest {@link OrderService#getOrders()}
     * @utbot.invokes {@link OrderRepository#findAll()}
     * @utbot.returnsFrom {@code return orderRepository.findAll();}
     * @utbot.throwsException {@link org.utbot.framework.plugin.api.TimeoutException} in: return orderRepository.findAll();
     */
```
The last line is erroneous. We should not see utbot exceptions in summaries.

**Additional context**

Previously fixed bug with similar error:
- #1739 

Connected feature request:
- #1833

**Comment by sofurihafe** [comment]
Could you please supply the issue with a code sample?
