### ISSUE TITLE
Cannot save test generation report in case of Timeout

### ISSUE THREAD

**Issue by EgorkaKulikov** [UnitTestBot/UTBotJava#1834]
**Description**

Sometimes tests generation fails with timeout. Test report genaration must work correctly anyway.

**To Reproduce**

Generate tests for the following code snippet:

```java
public class A {

    public int hangForSeconds(int seconds) {
        for (int i = 0; i < seconds; i++) {
                Thread.sleep(1000);
        }
        return seconds;
    }
}
```

**Visual proofs (screenshots, logs, images)**

![image](https://user-images.githubusercontent.com/29856383/220301400-d648e63c-3772-4186-a332-a89e3c1b2246.png)

**Additional context**

See bug https://github.com/UnitTestBot/UTBotJava/issues/1098 - it is a similar, but different issue
May be it's fix will be helpful.

**Comment by sofurihafe** [comment]
I have this popup when I generate tests for Spring project.
And I think it's due to zero(?) spring report support, not to timeouts.
