### ISSUE TITLE
JS. Empty Members list

### ISSUE THREAD

**Issue by alisevych** [UnitTestBot/UTBotJava#1902]
**Description**

Empty members list is shown in UnitTestBot dialog in debug IDE ideType=IU

**To Reproduce**

1. Run the 'utbot' project in IntelliJ Idea 2022.2.*
2. Set `ideType=IU`
3. Run Gradle task runIde
4. Open the attached project (or create JS project with a sample JS-file at root, used `bitOperators.js`).
5. Click on the file with functions and call action with shortcut

**Expected behavior**

Action dialog should contain functions of the file.

**Actual behavior**

Members list is empty.

**Visual proofs (screenshots, logs, images)**

![image](https://user-images.githubusercontent.com/37301492/223154882-f0d36b84-a8a3-43a7-9816-d00c68d5416a.png)

**Environment**

Windows 10 Pro
Debug IDEA Ultimate 2022.2.2

**Additional context**

The first test generation was successful.

**Comment by rudolf101** [comment]
This occurs when there are no top-level functions in the file when trying to start test generation from the context menu?

**Comment by alisevych** [comment]
[bitOperators.js.txt](https://github.com/UnitTestBot/UTBotJava/files/10899851/bitOperators.js.txt)
[Mar02JavaScript.iml.txt](https://github.com/UnitTestBot/UTBotJava/files/10899856/Mar02JavaScript.iml.txt)
[package.json.txt](https://github.com/UnitTestBot/UTBotJava/files/10899862/package.json.txt)
[package-lock.json.txt](https://github.com/UnitTestBot/UTBotJava/files/10899863/package-lock.json.txt)

**Comment by rudolf101** [comment]
It seems that when trying to run test generation from the context menu on a file containing a class, the methods of this class are not displayed in the dialog box.

Will be fixed
