### ISSUE TITLE
Find all @Configuration classes in Spring project

### ISSUE THREAD

**Issue by EgorkaKulikov** [UnitTestBot/UTBotJava#1921]
**Description**

We need to find all classes marked as `@Configuration` in Spring application.
They will be shown to user in UI to select one of them for testing purposes.

Sorting order is:
- config classes in test source root
- config classes in source root
- may be suggested new config class

**Context**

Implementation should be quite similar to test source root finding process.

**Comment by alisevych** [comment]
@EgorkaKulikov 
Can we also find and display java classes annotated with `@TestConfiguration`?
