### ISSUE TITLE
JS. First execution branch in `Recursion.factorial(n)` is not covered

### ISSUE THREAD

**Issue by alisevych** [UnitTestBot/UTBotJava#1958]
**Description**

Generated tests for `samples\commonRecursion.js` doesn't cover line 4 (n < 0 branch).

**To Reproduce**

1. [Install the latest IU plugin built from unit-test-bot/rc3102023 branch in IntelliJ Idea Ultimate 2022.3.2](https://github.com/UnitTestBot/UTBotJava/actions/runs/4427160548)
take **`utbot-intellij-IU-2023.3.*`** artefact 
2. Create/open a JavaScript project
3. Copy samples folder from `utbot-js` module and paste it into this project
4. Generate tests for Recursion.factorial(n) function in `samples/commonRecursion.js` 
5. Check the generated tests

**Expected behavior**

There should be a test for every execution branch.
Or at least UnitTestBot should try to cover all lines during timeout.

**Actual behavior**

4-th line with condition (n < 0) is not covered with tests.
There are only 2 tests generated stably: for (n==0) and (n > 0).
Test generation finishes before timeout is reached.

**Visual proofs (screenshots, logs, images)**

~~~javascript
const fileUnderTest = require("./../samples/commonRecursion.js")
const assert = require("assert")

///region Test suites for executable Recursion.factorial


it("testFactorial1", function ()
 {
    let recursion = new fileUnderTest.Recursion()
    
    let actual = recursion.factorial(0.0)
    
    assert.deepEqual(1, actual)
}
)

it("testFactorial2", function ()
 {
    let recursion = new fileUnderTest.Recursion()
    
    let actual = recursion.factorial(1.1125370618783376E-308)
    
    assert.deepEqual(-1.1125370618783376E-308, actual)
}
)

///endregion
~~~

**Environment**

Windows 10 Po
IntelliJ IDEA Ultimate 2022.3.2
Node.js 18.14.2

**Additional context**

Tried with the same result:
- Base / Fast mode 
- Timeout 10/60 sec

**Comment by alisevych** [comment]
#### Reproducing
on fresh version of unit-test-bot/rc3102023 branch. IU-plugin from this run:
https://github.com/UnitTestBot/UTBotJava/actions/runs/4434721564
The last commit for this run was dccfdade.

There is one more test with String input.
But a test with a number < 0 is not generated.

**Comment by rudolf101** [comment]
On the above run, one of the generated tests looks like this:
```javascript
it("testFactorial3", function ()
 {
    let recursion = new fileUnderTest.Recursion()
    
    let actual = recursion.factorial("\n\n")
    
    assert.deepEqual(0, actual)
}
)
```

Fun fact, this test *is* covering the first brunch (n<0) like this:
factorial("\n\n") -> return "\n\n" * factorial("\n\n" - 1) -> return "\n\n" * -1 -> 0
factorial("\n\n" - 1) -> factorial(-1) -> -1

JavaScript is weird
<img src="https://res.cloudinary.com/practicaldev/image/fetch/s--ZDtqrBOj--/c_limit%2Cf_auto%2Cfl_progressive%2Cq_auto%2Cw_880/https://github.com/damiancipolat/js_vs_memes/blob/master/doc/js_thanks.png%3Fraw%3Dtrue" data-canonical src="https://res.cloudinary.com/practicaldev/image/fetch/s--ZDtqrBOj--/c_limit%2Cf_auto%2Cfl_progressive%2Cq_auto%2Cw_880/https://github.com/damiancipolat/js_vs_memes/blob/master/doc/js_thanks.png%3Fraw%3Dtrue" width="600" height="600" />

**Comment by alisevych** [comment]
So, this bug was fixed after this PR was cherry-picked into release branch:
- #1909
