### ISSUE TITLE
Mock error (FileInputStream)

### ISSUE THREAD

**Issue by pogrebnoijak** [UnitTestBot/UTBotJava#1980]
**Description**

utbot-cli not generated anything if **java.io.FileInputStream.read** is called (FileInputStream mocked)

**To Reproduce**

```java
public class JavaIoFileInputStreamCheck {
    public void read(String s) throws IOException {
        java.io.FileInputStream fis = new java.io.FileInputStream(s);
        byte[] b = new byte[1000];
        int size = fis.read(b);		// fail there
    }
}
```

run utbot-cli:

```bash
java -jar utbot-cli-2023.03-SNAPSHOT.jar generate --classpath "/home/andrew/ex/build/classes/java/main" --source /home/andrew/ex/src/main/java/org/example/JavaIoFileInputStreamCheck.java --output Test.java org.example.JavaIoFileInputStreamCheck --mock-always java.io.FileInputStream
```

**Expected behavior**

Something generated

**Actual behavior**

Nothing generated (smth wrong with **fis.read**)

```java
package org.example;

public final class Test {
}
```

**Visual proofs (screenshots, logs, images)**

![FileInputStream](https://user-images.githubusercontent.com/23313906/226210124-b0cb946f-ae2b-468d-b4db-c7eb01b5b68d.png)

**Comment by tyuldashev** [comment]
Without force mock option `--mock-always java.io.FileInputStream` UTBot generates couple of tests, though they do not look very useful: one with NPE and second is disabled by sandboxing.
