### ISSUE TITLE
Calculate resource files absolute path in `utbot-spring-analyzer` internals

### ISSUE THREAD

**Issue by EgorkaKulikov** [UnitTestBot/UTBotJava#2037]
**Description**

Current implementation of `utbot-spring-analyzer` is designed to get absolute paths to resource files as parameter. These paths are required to be calculated in `utbot`. 

However, it seems to be easier to get these path directly in `utbot-spring-analyzer` as we are going to have significantly improved class loader. 

**Expected behavior**

The api of `utbot-spring-analyzer` is changed
Spring `ApplicationRunner` prepares all activities to obtain required absolute paths

**Potential alternatives**

Current implementation when parsing was considered to be done in caller process, not in calling.

**Comment by IlyaMuravjov** [comment]
It's worth noting that improved class loader is only helpful when it comes to finding "classpath:" resources. To find "file:" resources `utbot-spring-analyzer` should also be given path to the analyzed project.

**Comment by EgorkaKulikov** [comment]
Replaced with https://github.com/UnitTestBot/UTBotJava/issues/2120
