### ISSUE TITLE
Go. Empty test file is generated in a new Go project

### ISSUE THREAD

**Issue by alisevych** [UnitTestBot/UTBotJava#2044]
**Description**

Empty test file is generated for `samples.go`

**To Reproduce**

1. Open IntelliJ Idea 2022.3 Ultimate
2. Install [plugin built from unit-test-bot/rc2023.3 branch](https://github.com/UnitTestBot/UTBotJava/actions/runs/4487896210)
3. Create a new Go project 
4. Copy-paste `utbot-go/go-samples/simple` folder into it
5. Turn 'Experimental languages support' on
6. Use plugin to generate tests for any/all of the functions in `samples.go`

**Expected behavior**

Tests are supposed to be generated.

**Actual behavior**

Empty test file is generated.

**Visual proofs (screenshots, logs, images)**

~~~go
package simple

~~~

**Environment**

Windows 10 Pro
IntelliJ Idea 2022.3 Ultimate
Go 1.20.1

**Additional context**

In UTBotJava project tests are generated.

[Mar24Go.zip](https://github.com/UnitTestBot/UTBotJava/files/11063666/Mar24Go.zip)

**Comment by alisevych** [comment]
@Markoutte FYI

**Comment by egiptipavel** [comment]
Can you delete file `simple/supported_types.go` and try again?

**Comment by alisevych** [comment]
> Can you delete file `simple/supported_types.go` and try again?

That helped. Will check with both release versions..
