### ISSUE TITLE
Docs. Troubleshooting test run configuration with Java 17

### ISSUE THREAD

**Issue by alisevych** [UnitTestBot/UTBotJava#2047]
**Description**

Add Troubleshooting section in User guide on how to run tests with Java 17 using reflection.
In order to support user with bug 
- #2026 

Please consider the best place for Troubleshooting section.

**Expected behavior**

UnitTestBot sometimes cannot combine Object assemble model without using reflection.
Sometimes a private field needs to be set or got.
Reflection methods using setAccessible is forbidden in Java 17+.
User can add keys to the JVm in order to run the tests.
Otherwise UtUtils methods can fail.

**Environment**

IntelliJ IDEA Ultimate 2023.3.*

**Potential alternatives**

Possibility to add needed keys automatically can be very complex.
One can see the list of keys needed to run tests for UnitTestBot: [build.gradle.kts](build.gradle.kts)

**Context**

UnitTestBot plugin will be working on Java 17 starting from Release 2023.3

**Comment by olganaumenko** [comment]
@alisevych Please check the [Troubleshooting section](https://github.com/UnitTestBot/UTBotJava/wiki/Troubleshooting) in Wiki.

**Comment by alisevych** [comment]
I would correct the following wording not to mess the user:

`build an Object assemble model`  to just `build an Object`

Also the keys in the first part can be joined into one String so that it can be easily copy-pasted.

**Comment by olganaumenko** [comment]
@alisevych Please verify the [fix](https://github.com/UnitTestBot/UTBotJava/wiki/Troubleshooting).

**Comment by alisevych** [comment]
We've just identified that adding VM options to Run configuration doesn't work for Gradle run configuration in IDEA.

In case of Gradle project,
user needs to add VM options to gradle test task in `build.gradle` / `build.gradle.kts` file, like following:

![image](https://github.com/UnitTestBot/UTBotJava/assets/37301492/24076ae6-0cab-4a1e-a1be-8642ce677f50)

**Comment by alisevych** [comment]
The list of modules to open can be different.
User needs to open the java modules, which their classes are in.

For example, in OwnerControllerTest in spring-petclinic, there is setFiled called for `java.util.LinkedHashMap`
The following exception message is in console:

```java
   java.lang.reflect.InaccessibleObjectException: Unable to make field transient java.util.LinkedHashMap$Entry
java.util.LinkedHashMap.head accessible: module java.base does not "opens java.util" to unnamed module ...
```

So the following string should be added to VM options:
`"--add-opens", "java.base/java.util=ALL-UNNAMED"``
