### ISSUE TITLE
Failing assertion is generated for Spring class 

### ISSUE THREAD

**Issue by EgorkaKulikov** [UnitTestBot/UTBotJava#2060]
**Description**

Let's generate tests for the following code:

```java
private EntityManager em;

public List<User> listUsers() {
        return em.createQuery("from User ", User.class).getResultList();
    }
```

UtBot automatically detects that it is a Spring project, `NoConfiguration` mode is selected.

Generated test looks as follows:

```java

@Mock
public TypedQuery typedQueryMock;

@Test
@DisplayName("listUsers: EntityManagerCreateQuery -> return em.createQuery(\"from User \", User.class).getResultList()")
public void testListUsers_TypedQueryGetResultList() {
	(when(entityManagerMock.createQuery(any(), any()))).thenReturn(typedQueryMock);

	List actual = userDaoImp.listUsers();

	assertNull(actual);
}
```
`TypedQuery` type fully qualified name is `javax.persistence.TypedQuery`

**Expected behavior**

UtBot generates only passing tests.

**Actual behavior**

Generated test fails on the assertion.

**Visual proofs (screenshots, logs, images)**

![image](https://user-images.githubusercontent.com/29856383/228256110-5af2fe81-a7b8-43f4-aed7-22a005cea09c.png)

**Additional context**

The problem requires investigation, there are several possible situations:

- assertion is correct, but mocking is configured badly
- assertion is generated incorrectly
- there is a bug in engine that leads to incorrect test

**Comment by Damtev** [comment]
Please, specify the used configuration - the mocking or Spring implementors mode.

Also, it's unclear from the description what is `typedQueryMock` used in the generated test - please, provide more info.

**Comment by EgorkaKulikov** [comment]
Mode is Spring (it is detected automatically), `NoConfiguration` (implementors are not used).
typedQueryMock is an instance of type `javax.persistence.TypedQuery`

**Comment by Damtev** [comment]
About `typedQueryMock ` I mean - what is its definition in the generated test?

**Comment by Damtev** [comment]
it looks like a mocking of the method `TypedQuery#getResultList# is missed in the generated test. Need to check whether it exists in instrumentation and was lost in the code generation or it is a bug in the symbolic engine.

**Comment by EgorkaKulikov** [comment]
Instrumentation is empty, method `setupInstrumentation` just returns doing nothing, so it seems to be the symbolic engine bug.
