### ISSUE TITLE
Improve rendering Spring configuration name on UI

### ISSUE THREAD

**Issue by EgorkaKulikov** [UnitTestBot/UTBotJava#2079]
**Description**

Current representation of configs name on UI is the following:
- Fully qualified name for Java configs
- Full path for xml files

**Expected behavior**

It is suggested to show just simple names for the config if it is unique in project
otherwise:
- still use fqn for Java configs
- relative path to project for xml configs

**Potential alternatives**

Should be discussed with a team.

**Comment by IlyaMuravjov** [comment]
Potential alternative: display options the same way it's done in the top opened files tab list in Intellij IDEA itself (up to first folder required to uniquely identify the file among the other options)
![image](https://user-images.githubusercontent.com/71839386/228856453-9f3048c9-dbb6-4d08-a907-ccb6957c4b11.png)

Possible enhancement:
* [Preview list items with Java class and xml file icons](https://jetbrains.design/intellij/controls/drop_down/#28)
* [Group Java class and xml configurations](https://jetbrains.design/intellij/controls/drop_down/#25)
* [Disable `Mocking strategy` label when configuration is selected](https://jetbrains.design/intellij/controls/input_field/#10)

**Comment by EgorkaKulikov** [comment]
About suggested enhancements:

1) A good idea, if it is not hard to implement. May be for further iterations.
2) Andrey implemented grouping to show all java configs before all xml configs
3) Mocking strategy is disabled when config is selected. If you found a scenario with another behavior, show it to me, please.

**Comment by IlyaMuravjov** [comment]
2. I mean something like this
![image](https://user-images.githubusercontent.com/71839386/229106454-aab3889c-3cec-4b4f-a26c-c450c9857359.png)
3. Currently the combo box gets disabled, but the label next to it does not

**Comment by EgorkaKulikov** [comment]
I agree, points 2 and 3 will be implemented.
Name pruning idea is also good.

**Comment by EgorkaKulikov** [comment]
Point 3 is fixed here https://github.com/UnitTestBot/UTBotJava/pull/2088

**Comment by EgorkaKulikov** [comment]
Point 2 is fixed in #2090

**Comment by EgorkaKulikov** [comment]
Names shortening is fixed in https://github.com/UnitTestBot/UTBotJava/pull/2096
