### ISSUE TITLE
Parse XML-based Spring configurations excluding external links

### ISSUE THREAD

**Issue by alisevych** [UnitTestBot/UTBotJava#2132]
**Description**

XML-based configurations may contain external link(s).
Parsing can initiate connections to these links.

**Expected behavior**

Parse XML-based Spring configurations safely excluding external links.
Then we can use such XML-files and get information about Bean definitions from them.

**Environment**

IntelliJ IDEA 2022.3 - 2023.1

**Potential alternatives**

Currently parsing of such XML-based configurations is skipped:
- #2126

While XML-based configurations are supported:
- #2041

**Comment by alisevych** [comment]
There can be XML-files in resources and other project folders that contain links.
For example, settings.xml example for Maven configuration contains many links.
```xml
<settings xmlns="http://maven.apache.org/SETTINGS/1.0.0"
          xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
          xsi:schemaLocation="http://maven.apache.org/SETTINGS/1.0.0 http://maven.apache.org/xsd/settings-1.0.0.xsd">

<mirror>
    <url> ... </url>
</mirror>

<repository>
...
```
pom.xml contains:
```xml
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
```

**Comment by EgorkaKulikov** [comment]
Fixed in https://github.com/UnitTestBot/UTBotJava/pull/2163
