### ISSUE TITLE
Support activating multiple profiles via special expression

### ISSUE THREAD

**Issue by EgorkaKulikov** [UnitTestBot/UTBotJava#2186]
**Description**

Profile expression is stored in `ApplicationData.profileExpression` in `utbot-spring-analyzer`.

We hope that in most cases just one profile like "test" name will be sent.
However, user may send some rubbish like "petya%\'zuev" - will we really rollback to default profile in such case?

More than that, Spring allows to send some logical expressions like "prod|web". We should investigate possible formats of this expressions and support their parsing in utbot-spring-analyzer.

**Context**

Method `EnvironmentFactory.parseProfileExpression` should be implemented.

**Comment by alisevych** [comment]
What if @Profile and @Configuration are added to Java classes? [See example here](https://howtodoinjava.com/spring-boot/spring-profiles/#21-using-profile)
If user selects a profile - then it should have higher priority than configuration. Or...
It seems that to avoid such conflicts user can choose either profile(s), or configuration.

**Comment by alisevych** [comment]
Profile activation:
1. comma-separated in properties files, example: `spring.profiles.active=dev,hsqldb`
2. expressions in annotations: `@Profile("!prod")` 

Profile specific properties can also be defined using the naming convention application-{profile}.properties.

**Comment by EgorkaKulikov** [comment]
@tepa46 found a great article https://www.concretepage.com/spring-5/spring-profiles#Expression
It seems that we may have logical expressions on beans defining should we activate them or not. But for setting active profiles we should just pass their name(s) in comma-separated way.
