### ISSUE TITLE
Strange test without asserts is generated by Fuzzer

### ISSUE THREAD

**Issue by EgorkaKulikov** [UnitTestBot/UTBotJava#2194]
**To Reproduce**

1. Set fuzzing ratio to 100% in additional settings.
2. Generate tests for method `BaseEntity.setId` from `spring-petclinic` project.
with standard settings in main dialog window

**Expected behavior**

One BaseEntity$setId method call is expected.

**Actual behavior**

It seems strange. At least, it does not have asserts. The mutation is also strange - what happens, why to setters are used?

**Screenshots, logs**

Generated test looks as follows:

```java
@Test
@DisplayName("setId: id = -3 (mutated from -1)")
public void testSetId() {
  BaseEntity baseEntity = new BaseEntity();
  baseEntity.setId(1);
  
  baseEntity.setId(-3);
}
```

**Additional context**

Note that the reason of this problem may be:
- in Spring specific of this project
- in Fuzzer
- in Codegen that cannot represent fuzzer output

**Comment by sofurihafe** [comment]
Reproduced on clean project with no Spring. My bet is there is no assertion because of method being void.
```java
public final class BaseEntityTest {
    ///region Test suites for executable BaseEntity.setId

    ///region FUZZER: SUCCESSFUL EXECUTIONS for method setId(java.lang.Integer)

    /**
     * @utbot.classUnderTest {@link BaseEntity}
     * @utbot.methodUnderTest {@link BaseEntity#setId(Integer)}
     */
    @Test
    @DisplayName("setId: id = 3 (mutated from positive)")
    public void testSetId() {
        BaseEntity baseEntity = new BaseEntity();

        baseEntity.setId(3);
    }
    ///endregion

    ///endregion
}
```
