### ISSUE TITLE
Improve assemble models constructing in fuzzer

### ISSUE THREAD

**Issue by EgorkaKulikov** [UnitTestBot/UTBotJava#2221]
**Description**

Consider generating Spring integration tests for `spring-boot-testing` project method `OrderService.save`

The following test is generated:

```java
@Test(description = "createOrder: order = Order()")
    public void testCreateOrder() {
        // begin repository fill up
        Order order = new Order();
        order.setPrice(Double.NEGATIVE_INFINITY);
        order.setQty(Integer.MIN_VALUE);

       <...>
        assertEquals(expected, actual);
    }
```

**Expected behavior**

Assemble model is created, so the following code is generated:

```java
Order order = new Order(Double.NEGATIVE_INFINITY, Integer.MIN_VALUE);
```

**Context**

It seems that the problem is in Lombok specific of project under test.

**Comment by IlyaMuravjov** [comment]
Lombok doesn't generate two argument constructor, so here we can only use all argument constructor explicitly setting default values `new Order(0L, null, Double.NEGATIVE_INFINITY, Integer.MIN_VALUE);`

**Comment by EgorkaKulikov** [comment]
Debugged, all models are actually correct.
