### ISSUE TITLE
Avoid hardcoding table and repository names in Spring integration tests generator

### ISSUE THREAD

**Issue by EgorkaKulikov** [UnitTestBot/UTBotJava#2225]
**Description**

Current implementation of Spring integration testing has the following lines:

```java
// TODO properly detect which repositories need to be cleared, right now "orders" is hardcoded
val sql = "TRUNCATE TABLE orders"
```

**Expected behavior**

We need to avoid hardcode and obtain table and repository names from `stateBefore.thisInstance.utAutowiredModel.repoContent`

**Comment by IlyaMuravjov** [comment]
This is a bit less straightforward, because here we need table name and in `repoContent` there's only bean name. So either here or when creating `repoContent` we need to determine table names by inspecting corresponding `@Entity` annotation.

**Comment by alisevych** [comment]
Already done #2274
