### ISSUE TITLE
Convert `UtExecutionInstrumentation` from object to class

### ISSUE THREAD

**Issue by EgorkaKulikov** [UnitTestBot/UTBotJava#2226]
**Description**

`UtExecutionInstrumentation` is not a singleton by design.
However, it was implemented like this because of some problems with serialization.
They need to be fixed now because we introduce `SpringUtExecutionInstrumentation` and using singletons becomes much more inconvenient.

**Comment by IlyaMuravjov** [comment]
Completed in #2411
