### ISSUE TITLE
Spring Integration tests UI changes

### ISSUE THREAD

**Issue by alisevych** [UnitTestBot/UTBotJava#2266]
**Tests type and configuration**

Unit tests can be generated in `No Configuration` and `Spring configuration` mode.
Integration tests can be generated only with existing `Spring configuration`.

**Tests type and mock strategy**

Unit tests are generated with Engine only.
   - in `No configuration` mode any mock strategy can be used, default one is `Mock everything outside the class`.
   - in `Spring configuration` mode  is defaulted to `Mock using Spring configuration` and disabled.
  
Integration tests are generated with Fuzzing only, so mocking is defaulted to `Do not mock` and disabled.

**Tests type and other settings**

- [x] When `No Configuration` or `XML configuration` is selected, **Tests type**  is disabled and defaulted to `Unit tests`.
- [x] When existing **Spring configuration** is selected _(excluding XML configurations)_, **Tests type** is enabled and two options available: `Integration tests` and `Unit tests`.
- [x] When `Integration tests` is selected, **Test frameworks** must contain `JUnit4` and `JUnit5`
_`TestNg` must disappear from the list of suggestions._
- [x] When `Integration tests` is selected, `XML configuration` list must disappear from the list of suggestions in **Spring configuration**.

**Environment**

IntelliJ IDEA Ultimate 2023.1

**Comment by IlyaMuravjov** [comment]
Right now fuzzer can only generate `null` for most of the interface types (except some collections, for which custom `ValueProvider`s have been written). When we can't generate value other than `null` we should at least consider using mocks, which will contradict the premise of this issue, stating that: "[if we use] fuzzing only, [then] mocking is not available at all"

**Comment by alisevych** [comment]
@IlyaMuravjov This issue is about settings available on UI only.
**Currently** Fuzzing is not supporting mocks. So Mocking settings should not be available.

**Comment by alisevych** [comment]
@EgorkaKulikov 
Let's consider the following conflict case:
- User selects XML-based configuration in **Spring configuration** field.
- User selects `Integration tests` in **Tests type**

Shall we hide `Integration tests` after the first step?

**Comment by alisevych** [comment]
Also I would not exclude `XML configuration` list from suggestions when `Integration tests` are selected.
Just if user selects one of XMLs, `Unit tests` are selected.
Why?
To keep priority and consistency of `Spring configuration` control.
