### ISSUE TITLE
Investigate how to customize summarization for Spring project

### ISSUE THREAD

**Issue by EgorkaKulikov** [UnitTestBot/UTBotJava#2322]
**Description**

After the quick look it seems that summarization results "as is" are not very informative and convenient. Let's suggest how we would like to modify it. 

Do not forget that summarization consists of:
- test method names
- display names (shown in unit tests runner)
- doc comments

First of all, we should just suggest the design plan of new summaries and discuss it.
After that, we will create separate issues/pull requests for implementation

**Comment by IlyaMuravjov** [comment]
In the doc comment we can show covered lines of the method under test. 

For example, let's consider the following method under test:
```java
@GetMapping("/owners")
public String processFindForm(@RequestParam(defaultValue = "1") int page, Owner owner, BindingResult result,
		Model model) {
	// allow parameterless GET request for /owners to return all records
	if (owner.getLastName() == null) {
		owner.setLastName(""); // empty string signifies broadest possible search
	}

	// find owners by last name
	Page<Owner> ownersResults = findPaginatedForOwnersLastName(page, owner.getLastName());
	if (ownersResults.isEmpty()) {
		// no owners found
		result.rejectValue("lastName", "notFound", "not found");
		return "owners/findOwners";
	}

	if (ownersResults.getTotalElements() == 1) {
		// 1 owner found
		owner = ownersResults.iterator().next();
		return "redirect:/owners/" + owner.getId();
	}

	// multiple owners found
	return addPaginationModel(page, model, ownersResults);
}
```
Then one of the tests may look like this:
```java
/**
 * Covered lines (... in place of uncovered fragments):
 * <pre>
 * <code>
 *     
 * // allow parameterless GET request for /owners to return all records
 * if (owner.getLastName() == null) {
 * 	...
 * }
 *
 * // find owners by last name
 * Page<Owner> ownersResults = findPaginatedForOwnersLastName(page, owner.getLastName());
 * if (ownersResults.isEmpty()) {
 * 	...
 * }
 *
 * if (ownersResults.getTotalElements() == 1) {
 * 	// 1 owner found
 * 	owner = ownersResults.iterator().next();
 * 	return "redirect:/owners/" + owner.getId();
 * }
 *
 * ...
 * 
 * </code>
 * </pre>
 */
@Test
public void testProcessFindFormByFuzzer() {
	Owner owner = new Owner();
	owner.setAddress("-3");
	owner.setCity("-3");
	owner.setTelephone("-3");
	owner.setFirstName("XZ");
	owner.setLastName("-3");
	owner.setId(Integer.MAX_VALUE);
	ownerRepository.save(owner);

	String actual = ownerController.processFindForm(1, owner, null, null);

	String expected = "redirect:/owners/1";
	assertEquals(expected, actual);
}
```
Worth noting that if we settle on this approach, I think it's would be better to not only show lines that have covered instructions, but also to show lines that are adjacent to covered lines and don't have any instructions at all (e.g. comments and variable declarations).

**Comment by IlyaMuravjov** [comment]
We should also consider documenting coverage percentage for every test, as well as the return statement used to exit method under test.

**Comment by sofurihafe** [comment]
Current list of enhancements:
1. #2376
2. Missing summary texts and display names (petclinic, VetController#showVetList)
3. Whole method in display name (petclinic, CrashController#triggerException)
4. *Remove exception messages (petclinic, CrashController#triggerException)
5. Get rid of `id =` and come up with heuristics for repository saving (#2219)
