### ISSUE TITLE
Refactor CgSpringVariableConstructor

### ISSUE THREAD

**Issue by EgorkaKulikov** [UnitTestBot/UTBotJava#2326]
**Description**

Current design of `CgSpringVariableConstructor` is bad.

The following action is repeated three times for different annotations:
- we try to find a variable
- if variable is already created, use some custom fields construction

We can possibly implement some kind of Map<Annotation, ProcessingDelegate> and iterate by it.

**Comment by IlyaMuravjov** [comment]
I think, it's better to have some sort of `List<CgFieldManager>` where `CgFieldManager` is:
```kotlin
interface CgFieldManager {
    fun createFieldIfNeeded(model: UtModel): CgField?

    fun overrideValueCreationIfNeeded(model: UtModel): CgValue?
}
```
Here `CgFieldCreator` can encapsulate logic related to use of some kind of fields. For example, `CgAutowiredFieldManager` can encapsulate logic needed for recognition of bean models, creating and annotating corresponding fields, and construction of values for such models.
