### ISSUE TITLE
Investigate how to create specific tests for Spring controllers

### ISSUE THREAD

**Issue by EgorkaKulikov** [UnitTestBot/UTBotJava#2345]
**Description**

In accordance with some articles, unit tests for the controllers may be created a little bit different than for services
https://salithachathuranga94.medium.com/unit-and-integration-testing-in-spring-boot-micro-service-901fc53b0dff

We should investigate:
- how it works in details (e.g. the difference between `@Mock` and `@MockBean`)
- is it really useful 
- is it possible to implement smth like this in UtBot

**Comment by IlyaMuravjov** [comment]
I am not sure if we are capable of generating tests shown in linked article as unit tests, since although they use a lot of mocks, they still do seem to require starting an application.
