### ISSUE TITLE
occurred ExecutionPhaseError in the generated test

### ISSUE THREAD

**Issue by harzss** [UnitTestBot/UTBotJava#2352]
**Description**

I use the latest main utbot-cli ，but an error test with ExecutionPhaseError is generated 

**Expected behavior**

Test cases can be generated normally or exceptions can be handled correctly

**Actual behavior**

An error test with ExecutionPhaseError is generated 

**Visual proofs (screenshots, logs, images)**

~~~java
public void testFail_errors() {
assertThrows(org.utbot.instrumentation.instrumentation.execution.phases.ExecutionPhaseError.class, () -> xxxx);
}
~~~

**Environment**

java version: 11
utbot-cli version: latest main

**Comment by alisevych** [comment]
@harzss 
If you still face the issue, please provide the details of your case.
Class or method under test.
Thank you in advance.
