### ISSUE TITLE
No tests for unit tests when Fuzzer is enabled

### ISSUE THREAD

**Issue by sofurihafe** [UnitTestBot/UTBotJava#2393]
**Description**

When there is at least 1% fuzzer time value, no tests are generated.

**To Reproduce**

1. Open **AnimalsAndPeople** project.
2. Make (0% < fuzzer value < 100%).
3. Generate unit test without configuration with 60 seconds timeout for *NamesService:getAllNames()*.
4. Verify that *no tests were generated*

**Expected behavior**

One test should be generated by Symbolic Engine.

**Actual behavior**

No tests are being generated.

**Comment by alisevych** [comment]
@sofurihafe 
Please attach `AnimalsAndPeople` project

**Comment by sofurihafe** [comment]
@alisevych, done.
