### ISSUE TITLE
Generated tests can't be run in some Gradle projects

### ISSUE THREAD

**Issue by EgorkaKulikov** [UnitTestBot/UTBotJava#245]
**Description**

Tests generated with UtBot sometimes can not be run via standard Intellij Idea mechanism.

**To Reproduce**

1) Create Gradle project without any custom settings
2) Add an arbitrary class and generate tests for it with JUnit5
3) Try to run generated tests

**Expected behavior**

Tests are successfully run in Intellij Idea

**Actual behavior**

`Test events were not received` error occurs

**Additional context**

This problem may be fixed manually adding the following code into `build,gradle` file:

```kotlin
test {
    useJUnit()
    useTestNG()
    useJUnitPlatform()
}
```

But it is not obvious how to do it programmatically. 
The related question was sent to Intellij Support https://intellij-support.jetbrains.com/hc/en-us/community/posts/6168668718226-Enable-Gradle-native-support-programmatically

**Comment by EgorkaKulikov** [comment]
@denis-fokin let's discuss, what shall we do with it - JetBrains support says there is no good api solution to do it.

**Comment by alisevych** [comment]
The suggested solution is just notifying the user about the conflict. Please see the details below.

In Gradle Test task only one runner is used. So only JUnit5 tests will be run for the following task definition:
```
test {
    useJUnit()
    useTestNG()
    useJUnitPlatform()
}
```
That can be managed with a) commenting-uncommenting runners; b) additional test task creation, like that:
```
test {
    useJUnitPlatform()
}

tasks.register('generatedTest', Test) {
    description = 'Runs UTBot generated tests.'
    group = 'verification'
    useTestNG()
}

check.dependsOn generatedTest
```

There are many possible Gradle tasks existing configurations. There is a potential risk to corrupt them if changing that straightly.

So the suggested solution is just notifying the user about the conflict. 
"There are several test frameworks in the project. There are several configuration. Please refer to documentation:"
And suggesting them a link to the documentation - describing how to resolve this conflict.
Gradle - https://docs.gradle.org/current/userguide/java_testing.html#sec:configuring_java_integration_tests
Maven - https://maven.apache.org/surefire/maven-surefire-plugin/examples/providers.html
IDEA - https://www.jetbrains.com/help/idea/run-debug-configuration.html#compound-configs
