### ISSUE TITLE
Public constructors are not used when available

### ISSUE THREAD

**Issue by alisevych** [UnitTestBot/UTBotJava#2633]
**Description**

Generated tests for ClassWithComplicatedMethods use UtUtils method createInstance,
while there are public constructors.

**To Reproduce**

1. Install [UnitTestBot **-IU-** plugin built from main](https://github.com/UnitTestBot/UTBotJava/actions/runs/6355322622) in IntelliJ IDEA
2. Open `utbot-sample` module  in `UTBotJava` project
3. Generate tests for `ClassWithComplicatedMethods `
4. Find `createInstance` calls in generated tests

**Expected behavior**

ClassWithComplicatedMethods has public constructors with a and b parameters.
Is it expected that they are used? Only `a` is used in path constraints.

**Actual behavior**

createInstance is called in all tests generated with Symbolic execution

**Screenshots, logs**

~~~java
    ///region SYMBOLIC EXECUTION: SUCCESSFUL EXECUTIONS for method applyMethodWithSideEffectAndReturn(int)

    /**
     * @utbot.classUnderTest {@link ClassWithComplicatedMethods}
     * @utbot.methodUnderTest {@link ClassWithComplicatedMethods#applyMethodWithSideEffectAndReturn(int)}
     * @utbot.executesCondition {@code (a == 2821): False}
     * @utbot.invokes org.utbot.examples.make.symbolic.ClassWithComplicatedMethods#methodWithSideEffect(int)
     */
    @Test
    @DisplayName("applyMethodWithSideEffectAndReturn: ClassWithComplicatedMethodsMethodWithSideEffect -> return this")
    public void testApplyMethodWithSideEffectAndReturn_ANotEquals2821() throws Exception {
        ClassWithComplicatedMethods classWithComplicatedMethods = ((ClassWithComplicatedMethods) createInstance("org.utbot.examples.make.symbolic.ClassWithComplicatedMethods"));
        classWithComplicatedMethods.a = 15;

        ClassWithComplicatedMethods actual = classWithComplicatedMethods.applyMethodWithSideEffectAndReturn(1);

        int classWithComplicatedMethodsA = classWithComplicatedMethods.a;
        int actualA = actual.a;
        assertEquals(classWithComplicatedMethodsA, actualA);

        int finalClassWithComplicatedMethodsA = classWithComplicatedMethods.a;

        assertEquals(2821, finalClassWithComplicatedMethodsA);
    }
    ///endregion
~~~

**Environment**

IntelliJ IDEA version - Ultimate 2023.2
Project - Gradle
JDK - 17

**Comment by IlyaMuravjov** [comment]
No, it's not expected that these constructor are used, because they do not directly assign their parameters to fields.

Here are the constructors in question:
```java
public ClassWithComplicatedMethods(int a, int b) {
    UtMock.assume(a > 10);
    UtMock.assume(b > 10);

    this.a = a + b;
}

public ClassWithComplicatedMethods(double a, double b) {
    UtMock.assume(a > 0);
    UtMock.assume(b > 0);

    this.a = (int) (a + b);
}
```
If we want to get `ClassWithComplicatedMethods` instance with field `a` equal to `15`, we can't just call one of these constructors and pass `a=15` and arbitrary value of `b`.
