### ISSUE TITLE
Mock for LocalDate is created with same variable name as mock for PetType

### ISSUE THREAD

**Issue by alisevych** [UnitTestBot/UTBotJava#2638]
**Description**

There are two variables with name `petTypeMock` created in Unit tests for `Pet`

**To Reproduce**

1. Install **-IU-**  [UnitTestBot plugin ](https://github.com/UnitTestBot/UTBotJava/actions/runs/6379925168) in IntelliJ IDEA
2. Open `spring-petclinic`
3. Generate `Unit tests` for `Pet` with `PetClinicApplication` / No Configuration

**Expected behavior**

No mock for LocalDate is expected.
Variables for mocks should be with unique consistent names.
Tests should be compiled.

**Actual behavior**

There is mock for LocalDate.
There are two variables with name `petTypeMock`.
Tests are not compiling.

**Screenshots, logs**

![image](https://github.com/UnitTestBot/UTBotJava/assets/37301492/f4a1733d-f09d-435a-9ee4-ab479cd2e759)

![image](https://github.com/UnitTestBot/UTBotJava/assets/37301492/4c9c9228-d941-4cb3-8ec1-99cbf340221a)

**Environment**

IntelliJ IDEA version - Community 2023.2
Project - Maven
JDK - 17

**Comment by EgorkaKulikov** [comment]
It is a pity that this bug reproduced again. We have tried to fix it at least five times.
 
The general problem is that we do not have unique identifiers of `UtModel`s in the whole test class, just per execution. It causes problems when we need to group all models related to current class variable in Spring. Although we introduced so-called `UtmodelWrapper` and managed to fix the problem in 99,9% situations, it is not still advanced. 

Hope it is a really seldom situation and users will not face it.
