### ISSUE TITLE
"Array is empty" error message from ExecutionDistance class in utbot-summary module

### ISSUE THREAD

**Issue by amandelpie** [UnitTestBot/UTBotJava#267]
**Description**

For many summary test generation the following message "Array is empty" is raised

**To Reproduce**

Generate tests without mocks for the Stats class from guava-26

**Expected behavior**

Tests are supposed to be generated.

**Actual behavior**

Tests are not generated and the mentioned earlier exception is found

**Comment by amandelpie** [comment]
@Markoutte did you have this exception?

**Comment by Markoutte** [comment]
Looks like yes

**Comment by amandelpie** [comment]
![Stacktrace](https://user-images.githubusercontent.com/105506115/177494647-929f0416-232d-4c35-900b-77eb7759c80a.jpg)

**Comment by sergeypospelov** [comment]
Some extr acontext: If we use concrete execution not in the end of analysis, the engine produces `UtExecution` with the empty paths, because `ConcreteExecutor` doesn't know hot to translate bytecode to soot.

**Comment by amandelpie** [comment]
@sergeypospelov thanks, looks like now we have a temporary solution and it should be revisited in the nearest future

**Comment by amandelpie** [comment]
Fixed in the #567
