### ISSUE TITLE
Summary module generates empty comments. Should be no comment in this case.

### ISSUE THREAD

**Issue by amandelpie** [UnitTestBot/UTBotJava#280]
**Description**

There can be a situation where summary is a non-empty list with blank characters, like: regularStmt("\t\n").
As a result a comment is blank.
In this case the comment should not be shown.

This is a description of a probable bug which is known for many tests.

**Comment by amandelpie** [comment]
Could not reproduce this case, probably the problem is in the ```protected fun genWarnNotification(): String = " " //why is it empty?``` row in the SimpleCommentBuilder

**Comment by onewhl** [comment]
I reproduced the problem on the following code snippet:
```
public class Main {

    public static void main(String[] args) {
	// write your code here
    }
}
```
I got these results:
```
public class MainTest {
    ///region Test suites for executable com.company.Main.main

    ///region

    @Test
    @DisplayName("main: arg_0 = String[3]")
    public void testMainWithNonEmptyObjectArray() {
        String[] args = {"", "", ""};

        Main.main(args);
    }
    ///endregion

    ///region SUCCESSFUL EXECUTIONS for method main(java.lang.String[])

    /**
     *
     */
    @Test
    @DisplayName("main: ")
    public void testMain() {
        Main.main(null);
    }
    ///endregion

    ///endregion
}
```

@amandelpie you're totally right, the problem is that when the body is empty the tool calls `genWarnNotification()` for some reason, and it returns an empty string. It seems if the body is empty we shouldn't add JavaDoc at all.
