### ISSUE TITLE
Support Assumptions in Query  

### ISSUE THREAD

**Issue by SBOne-Kenobi** [UnitTestBot/UTBotJava#298]
**Description**

Now assumptions are supported on UtSolver level. That is inefficient and may create new bugs.

**Expected behavior**

Support assumptions on Query level.

**Comment by korifey** [comment]
> **Description**
> 
> Now assumptions are supported on UtSolver level. That is inefficient and may create new bugs.
> 
> **Expected behavior**
> 
> Support assumptions on Query level.

I don’t get. What is assumption? Could you provide an example?

**Comment by SBOne-Kenobi** [comment]
> > **Description**
> > Now assumptions are supported on UtSolver level. That is inefficient and may create new bugs.
> > **Expected behavior**
> > Support assumptions on Query level.
> 
> I don’t get. What is assumption? Could you provide an example?

Assumtion is type of constraint from here https://github.com/UnitTestBot/UTBotJava/pull/69
