### ISSUE TITLE
Absent class name in static constant usage

### ISSUE THREAD

**Issue by CaelmBleidd** [UnitTestBot/UTBotJava#300]
**Description**

If we generate tests using the contest estimator for `com.google.common.base.CaseFormat`, we will see that the resulting file does not compile because of absent class name in static constant usage: ` expectedFinalCaseFormat = .UPPER_CAMEL`.

**To Reproduce**

1. Run the contest estimator for `com.google.common.base.CaseFormat` with 300s time limit
2. Open generated file

**Expected behaviour**

Compilable file.

**Actual behaviour**

Generated file does not compile.

**Visual proofs (screenshots, logs, images)**
![image](https://user-images.githubusercontent.com/31047452/175558654-f8ab763f-0ee2-4dd9-bbad-3b35b4cf381e.png)

**Environment**

The default environment for the contest estimator.

**Additional context**

There is no additional context.

**Comment by EgorkaKulikov** [comment]
This issue is now blocked by 
https://github.com/UnitTestBot/UTBotJava/issues/457
and
https://github.com/UnitTestBot/UTBotJava/issues/457
