### ISSUE TITLE
Install appropriate version of TestNg in user project depending on JDK version

### ISSUE THREAD

**Issue by EgorkaKulikov** [UnitTestBot/UTBotJava#309]
**Description**

If JDK version is 11 or higher, we can still install release version of TestNg
Otherwise we should install 7.5 version as higher versions of this framework require JDK 11
https://groups.google.com/g/testng-users/c/BAFB1vk-kok

**Context**

This issue can be implemented after the increasing of intellij-gradle-plugin version from 2020.2

**Comment by tyuldashev** [comment]
Additional current problem is that even if user already have properly installed `Java 1.8 + TestNG 7.5` she still cannot select `TestNG` as test framework for test generation.
