### ISSUE TITLE
Prohibit resizing the plugin dialog window

### ISSUE THREAD

**Issue by EgorkaKulikov** [UnitTestBot/UTBotJava#326]
**Description**

Our dialog window looks ugly when we try to resize it. 
Current solution is to prohibit resizing because actually it seems that there is no need in it.

**Comment by Vassiliy-Kudryashov** [comment]
GenerateTestDialogWindow:
  ```
  init {
        title = "Generate tests with UtBot"
        setResizable(false) // The fix
        init()
    }
```
