### ISSUE TITLE
Extend TraversalContext

### ISSUE THREAD

**Issue by sergeypospelov** [UnitTestBot/UTBotJava#339]
**Description**

Now some fields related to a **single** Jimple instruction traversal (e.g., `queuedSymbolicStateUpdates`, `environment`) are implemented as mutable properties of `Traverser` and are reinitializied for every call of `Traverser::traverse` function. It looks weird.

The idea is to move all such properties to `TraversalContext` class.

Also there is a strange idea to put all the necessary information for the traversal (e.g., `TypeRegistry`, `Hierarchy`) inside `TraversalContext` class, so we could do analysis of a single `ExecutionState` having only a `TraversalContext`. Not sure if it's worthwhile.

**Expected behavior**

There are no properties related to a traversal of a single Jimple instruction in `Traverser`. All such properties are moved to `TraversalContext`.

**Potential alternatives**

Leave all as it is.

**Context**

You can also see `Traverser.kt` and `TraversalContext.kt` classes. See [this discussion](https://github.com/UnitTestBot/UTBotJava/discussions/84) on refactoring for more information.

**Comment by notify-bibi** [comment]
This will help to achieve concurrency at the stmt level. Can developers join concurrency

**Comment by JaneEugenia** [comment]
Outdated.
