### ISSUE TITLE
AssembleModelGenerator generates assemble model with fields different from the origin model

### ISSUE THREAD

**Issue by CaelmBleidd** [UnitTestBot/UTBotJava#372]
**Description**

AssembleModelGenerator generates an assemble model from the original model, but it chooses a constructor that affects fields, leading to a wrong expected behaviour in the test.

**To Reproduce**

Steps to reproduce the behaviour:

1. Run the 'antlr' project in IntelliJ Idea
2. Use the plugin to generate tests for `GrammarTransformPipeline.setGrammarPtr` with 60+s timeout
3. Second execution (I'm not sure how stable is this behaviour) produces described test.
4. In the generated test you can see it as `assertFalse(initialToken == finalToken)` that is highlighted as `always false`.

**Expected behaviour**

Successfully generated test that can be correctly executed.

**Actual behaviour**

Always false condition in assert

**Visual proof**

Generated test:
```java
@Test
public void testSetGrammarPtr2() throws Exception  {
    RuleAST ruleAST = new RuleAST(0);

    Token initialRuleASTToken = ruleAST.token;
    GrammarTransformPipeline.setGrammarPtr(null, ruleAST);
    Token finalRuleASTToken = ruleAST.token;
        
    assertFalse(initialRuleASTToken == finalRuleASTToken);
}
```

Symbolic state after: 
![image](https://user-images.githubusercontent.com/31047452/176902490-bfa34733-7e3e-41d4-83ff-6230b05d077a.png)
Here we can see that `PredAST(0)` will be created (where we will assign a new object in the token field), but the original expected `token` field is null.

Concrete state after:
![image](https://user-images.githubusercontent.com/31047452/176902755-7ed02052-0e3a-45f8-8e91-29843b9d7eb0.png)
Here we can see that the concrete executor found that we have initialised field `token` with some non-null value. Then, we found that it is different from the value of the models before (where this field is null). Therefore, we generate assertFalse for reference equality based on this information, but in reality, we take the same field twice, and this assertion cannot be satisfied.

**Environment**

time-limit 60+ seconds
mocks should be disabled

**Additional context**

There is no additional context.

**Comment by EgorkaKulikov** [comment]
The problem is highly likely in `ConstructorAnalyzer.isAppropriate` method

**Comment by Damtev** [comment]
Cannot reproduce in main from c9c2a0b44b2b56c67c1dbac81786a70ab32edf64
