### ISSUE TITLE
Existing test file is not overwritten

### ISSUE THREAD

**Issue by dtim** [UnitTestBot/UTBotJava#381]
**Description**

If a user generates a test suite for a class that already has a previously generated test suite, the existing file is not overwritten. Instead the generation fails. See _additional context_ below for possible cause.

**To Reproduce**

1. Generate a test suite for a class or a method. A new file should be created in the test root.
2. Generate another test suite for the same class without removing the file that has been created on the step 1.

**Expected behavior**

The old file content should be replaced with the new test suite.

**Actual behavior**

The new file is not created, the "Cannot Create Class ..." message is shown to the user.

**Visual proofs (screenshots, logs, images)**

![cannot-create-class-error](https://user-images.githubusercontent.com/336793/177058429-f5cf5e39-0736-48e5-bec1-9772fdf0223d.png)

**Environment**

OS: GNU/Linux (Ubuntu 20.04 LTS).
Test framework: JUnit4.

Other settings seems to be not relevant.

**Additional context**

I suppose that the problem appeared in the commit [https://github.com/UnitTestBot/UTBotJava/commit/10457f0b02b90c4f4082c57e74602cf913ca1df5](commit/10457f0) and is related to the usage of `DumbServiceImpl::runWhenSmart` method.

`DumbServiceImpl::runWhenSmart` does not immediately run the action, it puts it in a queue. The action is run when the IDE enters the "smart" mode. The action may take effect immediately, but it is not guaranteed.

It seems that the `testClass` variable still has `null` value when the check `testClass?.let { ... }` is performed. As a result, the file is not prepared for writing.

**Comment by alisevych** [comment]
Same error on on Windows 10 Pro, JUnit5.

**Comment by alisevych** [comment]
Verified on the last plugin from here: https://github.com/UnitTestBot/UTBotJava/actions/runs/2612161368
Not reproducing,
