### ISSUE TITLE
Support Lambda expressions inside Stream.filter() method

### ISSUE THREAD

**Issue by alisevych** [UnitTestBot/UTBotJava#397]
**Description**

Lambda expression inside Stream.filter() leads to test generation failure
when JDK 8/11 is used.

**Need to investigate**

**To Reproduce**

1. Open IntelliJ IDEA
2. Plugin is installed
3. A project with JDK 8/11 is opened
4. Add a class using Stream.filter() method with a lambda expression inside, like:

```
public class StreamExample {

    public void checkLambdaInFilter() {
        List<String> list = new ArrayList<>();
        list.add("a");
        list.add("b");
        list.add("c");
        list.stream()
                .filter(l -> l.contains("a"));
    }
}
```

**Expected behavior**

Tests are supposed to be generated.

**Actual behavior**

Failed to generate unit tests... popup is shown.
Timeout increasing is suggested, but that doesn't help.
**Failure is displayed in 2-3 seconds** , timeout is not reached.

**Visual proofs (screenshots, logs, images)**

![Lambda in Stream filter()](https://user-images.githubusercontent.com/37301492/177177265-3d72a903-7693-4328-b6d9-a3f50a7360c3.jpg)

Windows 10 Pro
IntelliJ IDEA 2022.1.3
JDK 8, 11

**Additional context**

Same code is analyzed successfully by UtBot when the class is added to UTBotJava Gradle project.

Also filter method **with method reference is working fine**, like that:

```
    public void checkLambdaInFilter() {
        List<String> list = new ArrayList<>();
        list.add("a");
        list.add("b");
        list.add("");
        list.stream()
                .filter(String::isEmpty);
    }

```

**Comment by Damtev** [comment]
Cannot reproduce - one test is generated as expected:
```java
@Test
@DisplayName("checkLambdaInFilter: ListAdd -> StreamFilter")
public void testCheckLambdaInFilter_StreamFilter() {
    StreamExample streamExample = new StreamExample();

    streamExample.checkLambdaInFilter();
}
```

Tested with JDK 11 `temurin-11.0.15` and  Corretto JDK 11 `jdk11.0.12_7`.

**Comment by alisevych** [comment]
Not reproducing any more on main branch
