### ISSUE TITLE
Inconsistent module SDK handling

### ISSUE THREAD

**Issue by dtim** [UnitTestBot/UTBotJava#401]
**Description**

If the project has different Java SDK configured for source and test modules, it is not very clear that SDK should be used by UTBot.

Historically the test module SDK is used (probably it may be related to concrete execution / instrumentation). On the other hand, Idea compiles the code using the source module SDK. If these two SDK are different, the behavior may be inconsistent, or the plugin may fall.

It is unclear how to work with projects with multiple source and tests modules that can have different settings.

Note: this is not yet a specific reproductible bug, it's more an architectural question that needs some experiments. Feel free to update this  description with more details.

**Comment by CaelmBleidd** [comment]
For now, we have fixes with another soot configuration and external process, it is not a relevant task anymore

**Comment by CaelmBleidd** [comment]
For now, we have fixes with another soot configuration and external process, it is not a relevant task anymore
