### ISSUE TITLE
HashMap with Enum as key - test generation fails

### ISSUE THREAD

**Issue by alisevych** [UnitTestBot/UTBotJava#436]
**Description**

Test generation fails for a method with HashMap using Enum as key.

**To Reproduce**

1. IntelliJ IDEA with UTBotJava plugin installed
2. A project with JDK 8/11 is opened
3. Add the following class:

```
public class MapWithEnum {

    public void createMapWithEnum() {
        Map<WorkDays, Integer> map = new HashMap<>();
        map.put(WorkDays.Monday, 112);
        map.put(WorkDays.Tuesday, 354);
        map.put(WorkDays.Friday, 567);
        map.remove(WorkDays.Tuesday);
    }

    public enum WorkDays {
        Monday,
        Tuesday,
        Wednesday,
        Thursday,
        Friday
    }
}
```

4. Run Generating tests with UTBot... for this class

**Expected behavior**

Tests are supposed to be generated.

**Actual behavior**

"Failed to generate unit tests for class MapWithEnum" error popup is shown in IDEA.
It is shown immediately after test generation is started.
Map.remove() method is crucial for the issue - without it generation passes.

**Visual proofs (screenshots, logs, images)**

![Map with Enum as key](https://user-images.githubusercontent.com/37301492/177525277-a241464d-c2cf-4f0c-abee-58c429887836.jpg)

**Environment**

Windows 10 Pro
IntelliJ IDEA 2022.1.3
checked on JDK 8 and 11, Gradle, Maven projects - same error

**Additional context**

Adding some input parameters to the method helps - fuzzer is generating tests.

Map.remove() method is crucial for the issue - without it generation passes.

Map with Enum as values - test generation passes.

**Comment by dtim** [comment]
Related to #230, #414

**Comment by dtim** [comment]
It seems that the problem is not enum-specific. The following example does not work as well:
```
    public HashMap<String, Integer> createMapWithString() {
        HashMap<String, Integer> map = new HashMap<>();
        map.put("tuesday", 354);
        map.remove("tuesday");
        return map;
    }
```

**Comment by CaelmBleidd** [comment]
Looks like it doesn't work when key and value have different types. Following examples doesn't work as well:

```kotlin
Integer mapPutAndGet() {
  Map<Long, Integer> values = new HashMap<>();

  values.put(new Long(1), new Integer(1));

  return values.get(new Long(1));
}
```
