### ISSUE TITLE
Cannot set static final java.io.InputStream field java.lang.System

### ISSUE THREAD

**Issue by CaelmBleidd** [UnitTestBot/UTBotJava#458]
**Description**

If we mock `java.util.Scanner` class, we get exceptions in the concrete executor -- cannot set field (see screenshot below)

**To Reproduce**

Steps to reproduce the behaviour:

1. Run any project in IntelliJ Idea
2. Create a method with scanner usage
3. Use the plugin to generate tests
4. Open the generated tests

**Expected behaviour**

Correctly generated tests for the method

**Actual behaviour**

Tests containing only exceptions

**Visual proofs**
![image](https://user-images.githubusercontent.com/31047452/177945296-260532f9-de8a-42ba-bdc1-b03468196812.png)
![image](https://user-images.githubusercontent.com/31047452/177945255-5042b367-829a-4606-8774-15f33d3671d6.png)

**Environment**

You need to add `java.util.Scanner` into the set of classes to mock always (in the settings of UTBot). 

**Additional context**
There is no additional context.

**Comment by sergeypospelov** [comment]
Reproduced
