### ISSUE TITLE
Failed to generate tests because canonical name was not found

### ISSUE THREAD

**Issue by sofurihafe** [UnitTestBot/UTBotJava#459]
**Description**

Tests generation failed because `ClassId.canonicalName` has thrown an exception

**To Reproduce**

1. Run Contest Estimator with method com.google.common.base.CaseFormat.* and 300s time limit.

**Actual behavior**
```java
    public void testTo_errors()
     {
        // Couldn't generate some tests. List of errors:
        // 
        // 1 occurrences of:
        // ClassId com.google.common.base.CaseFormat$1 does not have canonical name
    }
    
```

**Comment by dtim** [comment]
Seems to be related to anonymous classes.
