### ISSUE TITLE
Predicate.not() method support is needed

### ISSUE THREAD

**Issue by alisevych** [UnitTestBot/UTBotJava#555]
**Description**

In Java 11 there is a new static method introduced: Predicate.not()
Add its support for test generation.

**To Reproduce**

1. Set useFuzzing=false in settings.properties
2. A project with JDK 11 is opened in IntelliJ IDEA
3. Add the following Java class to it:

```
import java.util.function.Predicate;

public class test {

    public boolean testIsEqual(int a) {
        if (Predicate.isEqual(5).test(a)) {
            return true;
        } else {
            return false;
        }
    }

    public boolean testNot(int a) {
        if (Predicate.not(i -> i.equals(5)).test(a)) {
            return true;
        } else {
            return false;
        }
    }
}
```

4. Create tests with UTBot... for testIsEqual
5. Create tests with UTBot... for testNot

**Expected behavior**

4,5 Tests are generated successfully

**Actual behavior**

4. Tests are generated
5. Failed to generate tests error dialog is displayed.

**Environment**

IDEA 2022.1.3
Gradle project with JDK 11

**Comment by dtim** [comment]
Notes after a debugging session with @ArsenHD

`Predicate.not()` static creates a nested lambda via the call to `Predicate.negate()` on its parameter. The outer lambda (negated predicate) captures `this` reference of the nested lambda (original predicate), we can see it as the `cap0` field in the debugger.

There are several locations in the code (e.g., `recordInstanceFieldRead`) that tries to find a class to which this captured field belongs. As lambda does not have any "real" class which we could obtain by reflection (`ClassId.jClass` etc), the engine fails with the `ClassNotFoundException`.

**Comment by alisevych** [comment]
@Damtev Please note that it's reproducing on [the latest build from main](https://github.com/UnitTestBot/UTBotJava/actions/runs/3080551289)
