### ISSUE TITLE
Need to handle absence of Test Source root in Gradle project

### ISSUE THREAD

**Issue by alisevych** [UnitTestBot/UTBotJava#657]
**Description**

Need to handle the situation when there is no Test sources root in Gradle project.

**To Reproduce**

1. Run IntelliJ IDEA
2. Create a new Gradle project with JDK 8 / 11
3. Remove test folder from /src - to emulate the situation when there is NO test source root in a User's project
4. Add some class to the /src/main/java
5. Open "Create tests with UTBot..." dialog

**Expected behavior**

/src/test/utbot_tests is suggested to be created as Test source root

or

Some red notification that UTBot cannot generate tests before the User configures a Test source root manually - with a link to documentation on how to do that.

**Actual behavior**

"set test folder" is displayed as an available option in the dropdown
... button (where a user could select a folder) is disabled

**Visual proofs (screenshots, logs, images)**

![image](https://user-images.githubusercontent.com/37301492/182637978-42e7a95b-5daa-4c4a-b1b3-2991cb3f4df1.png)

**Environment**

IntelliJ IDEA Ultimate 2022.1.4

**Additional context**

Tests were run successfully - if utbot_tests folder was located inside /src/test folder

**Comment by alisevych** [comment]
@Vassiliy-Kudryashov 
Here are the example Gradle projects with modules **without** folder "/src/test"
https://github.com/JetBrains/intellij-ui-test-robot/tree/master/robot-server-plugin
https://github.com/HujiangTechnology/gradle_plugin_android_aspectjx

**Comment by nikitavlaev** [comment]
![image](https://user-images.githubusercontent.com/43010567/183127785-7f8062da-885c-4c5e-865a-9283e6c20660.png)
How about this solution?

**Comment by alisevych** [comment]
It would be good to add a link to how-to: https://www.jetbrains.com/help/idea/testing.html#add-test-root
