### ISSUE TITLE
Inconsistent DisplayName is generated for a Collection used as the only parameter

### ISSUE THREAD

**Issue by alisevych** [UnitTestBot/UTBotJava#684]
**Description**

Inconsistent DisplayName is generated for a Collection used as the only parameter.
For example:     @DisplayName("setParam:  and others")

**To Reproduce**

1. Open IntelliJ Idea 2022.1.4 with one of the latest UTBotJava installed 
2. Add the following class - a Collection is the only input parameter of the method

```
import java.util.List;

public class CheckFinalSet  {

    private List<String> resource;

    public  void setParam( List<String> param) {
        this.resource = param;
    }

}
```

3. Generate JUnit5 tests with "Not parametrized" option
4. Check the generated test

**Expected behavior**

DisplayName should contain a consistent text about the parameters

**Actual behavior**

DisplayName contains the following text: 
`"setParam:  and others"`

**Visual proofs (screenshots, logs, images)**

~~~
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.DisplayName;

import java.util.TreeMap;

public class CheckFinalSetTest {
    ///region Test suites for executable CheckFinalSet.setParam

    ///region

    @Test
    @DisplayName("setParam:  and others")
    public void testSetParam() {
        CheckFinalSet checkFinalSet = new CheckFinalSet();
        TreeMap param = new TreeMap();

        checkFinalSet.setParam(param);
    }
    ///endregion

    ///endregion

}
~~~

**Environment**

Windows 10 Pro
IDEA 2022.1.4
JDK 8

**Additional context**

Same text in annotation is generated for with Set, List, Map - used as the only parameter. 
If another parameter (String, int, etc.) the text contains the part before "and".
For instance:

`    @DisplayName("setParam: n > 0 and others")
`

**Comment by amandelpie** [comment]
Great, many thanks @alisevych

**Comment by onewhl** [comment]
I reproduced the issue on the today's build of the main branch.

Debugging helped me to understand that we build this display name based on the fuzzer's results.
I ran the plugin on the provided example in the issue, dived into `ModelBasednameSuggester#createDisplayName()` and got that we have only one fuzzed value, its summary is null. Then we generate information about parameters from values' summaries, but we don't check if they are null before adding "and others" ending.

@Markoutte could you please take a look at the issue and navigate how it could be fixed in a proper way?

**Comment by Markoutte** [comment]
Some fuzzed values can have no description indeed, therefore "and others" is added. I think, in case when no values are supplied at all the best way is to write something like "with generated values" or just omit it. Maybe something like this:

```patch
Index: utbot-summary/src/main/kotlin/org/utbot/summary/fuzzer/names/ModelBasedNameSuggester.kt
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/utbot-summary/src/main/kotlin/org/utbot/summary/fuzzer/names/ModelBasedNameSuggester.kt b/utbot-summary/src/main/kotlin/org/utbot/summary/fuzzer/names/ModelBasedNameSuggester.kt
--- a/utbot-summary/src/main/kotlin/org/utbot/summary/fuzzer/names/ModelBasedNameSuggester.kt	(revision 492f7fa5ed5e80543790ce493d95332c9761e2d1)
+++ b/utbot-summary/src/main/kotlin/org/utbot/summary/fuzzer/names/ModelBasedNameSuggester.kt	(date 1662012626921)
@@ -101,7 +101,12 @@
             .filterNotNull()
             .toList()
 
-        val parameters = summaries.joinToString(postfix = if (summaries.size < values.size) " and others" else "")
+        val postfix = when {
+            summaries.isEmpty() && values.isNotEmpty() -> "with generated values"
+            summaries.size < values.size -> " and others"
+            else -> ""
+        }
+        val parameters = summaries.joinToString(postfix = postfix)
 
         val returnValue = when(result) {
             is UtExecutionSuccess -> result.model.let { m ->
```

**Comment by onewhl** [comment]
@Markoutte thanks for explanation and solution! 
@alisevych would this solution resolve the ticket? Maxim and I discussed that it would be nice to provide description for collection value as well in the future (like "empty list"). But it sounds like a separate ticket (feature request maybe?).
