### ISSUE TITLE
Android Studio: Mockito dependencies installation (and maybe JUnit)

### ISSUE THREAD

**Issue by nikitavlaev** [UnitTestBot/UTBotJava#691]
**Description**

In Android Studio `mockito-core` is not installed correctly in Gradle project.
This leads to the project build failure.

Also, other dependencies should be checked for that error (`mockito-inline`, `JUnit`).

**To Reproduce**

1. Create new project in Android Studio
2. Add Android library
3. Use plugin to generate tests
4. Choose to configure mockito
5. Experience the build failure

**Expected behavior**

Required dependencies are supposed to be installed correctly.

**Actual behavior**

Build failure.

**Visual proofs (screenshots, logs, images)**

To be added.

**Environment**

Clean Gradle project in Android Studio.

**Additional context**

None.

**Comment by EgorkaKulikov** [comment]
This problem is actual for `mockito-core` and `junit5`

**Comment by tyuldashev** [comment]
Tested with Android Studio Chipmunk | 2021.2.1 Patch 2 and UTBot 2022.10.471.
