### ISSUE TITLE
Android Studio: generated test sources available to choose

### ISSUE THREAD

**Issue by nikitavlaev** [UnitTestBot/UTBotJava#692]
**Description**

In Android Studio after first test generation generated test sources (`build/generated`) become available.
They are needed to be filtered out.

**To Reproduce**

_Example:_

1. Create new project in Android Studio
2. Add Android library
3. Use plugin to generate tests
4. Use plugin to generate tests again, you should see `build/generated`

**Expected behavior**

No generated test sources should appear.

**Actual behavior**

Generated test sources appear.

**Visual proofs (screenshots, logs, images)**

To be added.

**Environment**

Android Studio

**Additional context**

None

**Comment by tyuldashev** [comment]
Tested with Android Studio Chipmunk | 2021.2.1 Patch 2 and UTBot 2022.10.471.
