### ISSUE TITLE
Lombok plugin is incompatible with latest Android Studio

### ISSUE THREAD

**Issue by alisevych** [UnitTestBot/UTBotJava#718]
**Description**

Last version of lombok plugin cannot be installed into last version of Android Studio.
Workaround is needed for the correct work of UTBot plugin.

**To Reproduce**

1. Install last version of Android Studio
2. Download last version of lombok plugin from here: https://plugins.jetbrains.com/plugin/6317-lombok/versions
3. Try to install it (File -> Settings -> Plugins -> Install from disk )

**Expected behavior**

Plugin is supposed to be installed - for the needs of UTBot plugin

**Actual behavior**

Version incompatibility error is shown. The plugin is not installed.

**Visual proofs (screenshots, logs, images)**

![image](https://user-images.githubusercontent.com/37301492/184343080-a9158e26-1f1c-4f7c-994c-1d9c1fec9d7d.png)

**Environment**

Windows 10 Pro
JRE 11
Android Studio 

**Additional context**

This is the step from installation instruction for UTBot Java plugin into Android Studio
https://github.com/UnitTestBot/UTBotJava/blob/main/docs/AndroidStudioSupport.md

**Comment by alisevych** [comment]
@nikitavlaev Is this plugin really needed for UTBot test generation? Or Lombok-free projects can work without it?

**Comment by nikitavlaev** [comment]
Lombok-free projects certainly do not require this plugin.
However, people frequently use it in their projects

**Comment by nikitavlaev** [comment]
Also, I've managed to install the plugin in the latest Android Studio 2021.2.1

**Comment by alisevych** [comment]
@nikitavlaev As Lombok plugin is not compulsory for UTBot test generation, may be it would be better to move this part to troubleshooting? 
https://github.com/UnitTestBot/UTBotJava/blob/main/docs/AndroidStudioSupport.md
