### ISSUE TITLE
JavaScript: UI method list contains class fields

### ISSUE THREAD

**Issue by tamarinvs19** [UnitTestBot/UTBotJava#722]
**Description**

Plugin dialog contains class fields in the list of methods.

**To Reproduce**

1. Run the JavaScript project in IntelliJ Idea with file `/scenarios/hello.js`
2. Write this code to file `/scenarios/hello.js`:
```
class MyTestClass {
    x = 100
}
```
3. Use plugin on class `MyTestClass` to generate tests
4. See to list of methods

**Expected behavior**

The table with methods is supposed to be empty.

**Actual behavior**

`x` field is present in the list of methods.

**Visual proofs (screenshots, logs, images)**

![ScreenshotFields](https://user-images.githubusercontent.com/23080942/184612178-747cb6f2-6cb5-4a4a-9086-83b8a1971d15.png)

**Environment**

_TestFramework_: Mocha
_OS_: Windows 10
_Intellij IDEA_: IntelliJ IDEA 2020.2 (Ultimate Edition), Build #IU-202.6397.94, built on July 27, 2020
_Runtime version_: 11.0.7+10-b944.20 amd64

**Comment by rudolf101** [comment]
@tamarinvs19 
Fixed with [commit](https://github.com/UnitTestBot/UTBotJava/commit/5ac594f6bfabf68519917da8a32b1b597babf2df)

**Comment by tamarinvs19** [comment]
OK
