### ISSUE TITLE
Name search at IDEA marketplace partially fails

### ISSUE THREAD

**Issue by JaneEugenia** [UnitTestBot/UTBotJava#745]
**Description**

If we want to install the UTBot plugin for the first time from IDEA marketplace, it can only be found in the marketplace by "UnitTest Bot" full of partial name request. If we type "UTBot", there are no search results.
Though, if the plugin has already been installed, the search gives you the result by "UTBot" request as well.

**To Reproduce**

1. Open IDEA Marketplace without UTBot plugin installed
2. Try typing UnitTest Bot and  UTBot to see the results

**Expected behavior**

The plugin should be found by both full or partial name requests.

**Actual behavior**

The plugin is only found by UniTest Bot name request

**Comment by Vassiliy-Kudryashov** [comment]
As for marketplace IDE sends request to server (like https://plugins.jetbrains.com/api/search/plugins?search=utb&build=IC-223.SNAPSHOT&max=10000) and query processing it up to server. Probably **plugin name** is the the only thing to match in this case.
