### ISSUE TITLE
JavaScript: Infinite loop

### ISSUE THREAD

**Issue by MusinaPolina** [UnitTestBot/UTBotJava#746]
**Description**

Infinite loop in incorrect realization of bin search (left boarder is always less than right one) leads to infinite work of test generation and it's impossible to stop the process gently.

**To Reproduce**

1. Run the JavaScript project in IntelliJ Idea with file `/scenarios/test.js`
2. Write this code to file `/scenarios/test.js`:

```javascript
class MyTest {
    wrongBinSearch(l, r) {
        let k = 10
        while (l < r) {
            let m = (l + r) / 2
            if (m < k) {
                l = m
            } else {
                r = m
            }
        }
      return l
    }
}
```

**Expected behavior**

Tests are supposed to be generated without CPU overloading.

**Actual behavior**

Test generation is running and create a lot of node.js processes that use almost all CPU.

**Environment**

TestFramework: Mocha
OS: Windows 11
Intellij IDEA: IntelliJ IDEA 2020.2 (Ultimate Edition), Build #IU-202.6397.94, built on July 27, 2020
Runtime version: 11.0.7+10-b944.20 amd64

**Comment by rudolf101** [comment]
@MusinaPolina
Fixed with [commit](https://github.com/UnitTestBot/UTBotJava/commit/76eced32ade242b9ab33c5d4303a98676f69fd3f).
