### ISSUE TITLE
Different coverage is generated for ClassWithEnum with JUnit5 and TestNg

### ISSUE THREAD

**Issue by EgorkaKulikov** [UnitTestBot/UTBotJava#777]
**Description**

Run `ClassWithEnumTest` on your local machine in PARAMETRIZED mode

If we use `TestNg` as test framework, the following code is generated:

```java
public static class StatusEnumTest {      
        @Test(dataProvider = "provideDataForValues")
        public void parameterizedTestsForValues(org.utbot.examples.enums.ClassWithEnum.StatusEnum[] expectedResult) {
            org.utbot.examples.enums.ClassWithEnum.StatusEnum[] actual = ClassWithEnum.StatusEnum.values();
            
            if (expectedResult == null) {
                assertNull(actual);
            } else {
                int expectedResultSize = expectedResult.length;
                assertEquals(expectedResultSize, actual.length);
                assertTrue(deepEquals(actual, expectedResult));
            }
        }
```

If we try to compile this code, the following error occurs:
```
error: non-static method deepEquals(Object,Object) cannot be referenced from a static context
                assertTrue(deepEquals(actual, expectedResult));
```

If we use `JUnit5` as test framework, there are no problems with compilation because... no `StaticEnumTest` class is generated at all!

**Expected behavior**

Investigate, please, what is an expected behavior here. Should we really create this test class or not and why this behavior depends on the selected test framework. After that I will fix all actual compilation problems.

**Comment by dtim** [comment]
I'm closing this issue as not reproducing / not actual. Please reopen it if you see this problem again.
