### ISSUE TITLE
Successful and tests with exceptions are put into one unnamed region

### ISSUE THREAD

**Issue by alisevych** [UnitTestBot/UTBotJava#823]
**Description**

There should be the following regions in the generated test class:
.Test suites for executable ... and sub-regions inside:
..SUCCESSFUL EXECUTIONS for method... 
..ERROR SUITE for method... 
..EXPLICITLY THROWN UNCHECKED EXCEPTIONS for method...
Now successful test  and tests with exceptions are put into one unnamed region - when there are some generated by Fuzzing.

**To Reproduce**

1. IntelliJ IDEA 2022.1.4 is running with UTBot installed (https://github.com/UnitTestBot/UTBotJava/actions/runs/2955784591)
2. Check that Fuzzing is on
3. Open/clone UTBotJava project
4. Open utbot-sample/src/main/java/org/utbot/examples/objects/ObjectWithPrimitivesExample.java
5. Generate tests for createObject method
6. Open Structure toolbar for the generated test

**Expected behavior**

Generated tests are supposed to be distributed into 3 sub-regions:
. SUCCESSFUL EXECUTIONS for method... 
. ERROR SUITE for method... 
. EXPLICITLY THROWN UNCHECKED EXCEPTIONS for method...

This is the screenshot from the demo made on July 25:
![Screenshot 2022-08-30 174515](https://user-images.githubusercontent.com/37301492/187469345-f466e696-278f-4854-8c48-cbf59d39a95a.jpg)

**Actual behavior**

There are only two regions: unnamed and ERROR suite.
Successful test and one with IAE are put together into unnamed region.

![image](https://user-images.githubusercontent.com/37301492/187469580-1c66e738-9706-4017-a885-8501b74c30c9.png)

**Environment**

Windows 10 Pro
IntelliJ IDEA 2022.1.4
JDK 11, language level 8

**Additional context**

Reproducing on other classes too - when there are tests generated by Fuzzing in the result test class.

**Comment by amandelpie** [comment]
Probably will be closed with the fix in #430

**Comment by amandelpie** [comment]
@alisevych I fixed this in the #858 , please check and close this ticket if it's fixed
