### ISSUE TITLE
Proper set of dependencies to integrate UnitTestBot family in the main branch

### ISSUE THREAD

**Issue by denis-fokin** [UnitTestBot/UTBotJava#833]
**Description**

In order to integrate UnitTestBot (UTB) Family in the `main` branch of the UTB, we need to check that all versions can be put together in the same `utbot-intellij` repository.

**Expected behavior**

All UTB implementations are in the same `utbot-intellij` module. The `runIde` task smoothly runs both for `IU` and `IC` IDE targets. If run for `IU`, all products have all needed dependency to be executed successfully.

**Environment**

Developer machine.

**Potential alternatives**

Target for particular IDEs: `PC`, `WS` and so on.

**Context**

There are a number of places that should be updated and a couple of sources that should be considered to find out proper versions of the IDE and dependencies.

The root `build.gradle` contains `runIde` target.

Follow https://github.com/JetBrains/gradle-intellij-plugin to update it.

Consider adding plugins in the plugin section.

Use `plugin.xml`, do not update since and until attributes in the `idea-version` tag. They are set in the `build.gradle` file.

Find out proper dependencies and add them as optional dependencies as it done for the AS support.

`<depends optional="true" config-file="withAndroid.xml">org.jetbrains.android</depends>`

**Comment by Vassiliy-Kudryashov** [comment]
All results were merged into **interns_main** branch
