### ISSUE TITLE
Log of concrete execution doesn't print exception anymore

### ISSUE THREAD

**Issue by Markoutte** [UnitTestBot/UTBotJava#870]
**Description**

At the moment, logs that are created by concrete execution don't contains printed exception anymore, but have too much info about data transfer between main process and child process.

**To Reproduce**

1. Enable logs using `~/.utbot/settings.properties`: `logConcreteExecutionErrors=true`
2. Run any test generation which leads to concrete execution failure. For example, #739
3. Find logs in temp folder: `~\AppData\Local\Temp\UTBot\utbot-childprocess-errors`
4. Open it.

**Expected behavior**

Log should contain some system information and an exception that is translated into broken test in main process.

**Actual behavior**

Log contains some child process problem (#848), many lines like this one:

```
16:59:27.308 | sent cmd: org.utbot.framework.concrete.UtConcreteExecutionResult@2efe6272
````

and no information about exception.

**Additional context**

Looks like this behavior was introduces with #748

**Comment by alisevych** [comment]
@Domonion Could you please raise the priority of this issue and consider its fix? It has big testability value. Currently we do not have any information about an error if it's not reproducing. For example: https://github.com/UnitTestBot/UTBotJava/issues/885#issuecomment-1240816750

**Comment by Domonion** [comment]
> Enable logs using `~/.utbot/settings.properties`: `logConcreteExecutionErrors=true`
I was not able to enable logs by gradle props, only in `UtSettings`

**Comment by alisevych** [comment]
@Domonion Please look for the same option in UtSettings - logConcreteExecutionErrors
FYI: All settings that you can set in settings.properties are present in UtSettings.
