### ISSUE TITLE
Util class design documentation

### ISSUE THREAD

**Issue by alisevych** [UnitTestBot/UTBotJava#930]
**Description**

Documentation on UtUtils class use cases.

**Details**

Rearrange design doc to be more strict and easy to understand.
Add it to the design docs in the project.

**Comment by olganaumenko** [comment]
It is just a link to insert into a resulting doc:
<img width="494" alt="ututils" src="https://user-images.githubusercontent.com/64418523/196719780-2603f141-e922-40fc-9a0a-533aaacc5c49.png">
