### ISSUE TITLE
State before and state after asserts for UtBot Python

### ISSUE THREAD

**Issue by tamarinvs19** [UnitTestBot/UTBotJava#986]
**Description**

Now we generate asserts only for the return value of the tested function. For a full check we need to assert function argument values and class field values if the testing function is class method.

**Expected behavior**

In order to add state assertions, we need to serialize arguments before and after function call (in Python), read it in Kotlin and then generate assertion code.

If the serialization process is unavailable for the field we should check only type.  

**Potential alternatives**

No alternatives.

**Context**

No special context.

**Comment by tyuldashev** [comment]
Seems it doesn't work in latest version of the plugin - no additional asserts are generated.
